### ISSUE TITLE
[Feature Request] Add multiple support for multiple languages

### ISSUE THREAD

**Issue by mpfans** [azerothcore/Keira3#1019]
Suggest add a language configuration file,when updating, you don't need to translate every time

**Comment by FrancescoBorzi** [comment]
@mpfans do you mean releasing Keira3 in different languages?

**Comment by mpfans** [comment]
> @mpfans do you mean releasing Keira3 in different languages?

Yes, you are right. It is recommended to make a configuration file for users to translate by themselves.

**Comment by Kitzunu** [comment]
I suppose you could add a dropdown menu on the first page (when logged out) for different languages, and also add it to the menu bar for when you are logged in.

as for how it would work from the source, I don't know if it is possible but for translating purposes it would be easy if it was constructed all in one file that overrides the original file if selected.

**Comment by willkillson** [comment]
Did a preliminary search on localizations with angular and came across this. Looks kinda easy...

https://angular.io/guide/i18n

**Comment by FrancescoBorzi** [comment]
this is a library we can use, I used it in another project as well:

https://github.com/ngneat/transloco

**Comment by FrancescoBorzi** [comment]
> Is there a plan for this?

we would like to but are too busy with other tasks at the moment

**Comment by Helias** [comment]
We could use this for the translations https://github.com/ngx-translate/core

**Comment by Helias** [comment]
@mpfans I've finished the multi-lang system in a PR, you can translate Keira3 texts into chinese if you want using the zh.json file https://github.com/azerothcore/Keira3/tree/multi-lang/src/assets/i18n
if you do, please send the file here or open a PR with the zh.json

**Comment by mpfans** [comment]
working
![image](https://user-images.githubusercontent.com/18187177/175490397-f09cb69a-fabb-46c3-800b-325359140d66.png)

**Comment by Helias** [comment]
very nice! thank you
