### ISSUE TITLE
ssh tunnel support

### ISSUE THREAD

**Issue by Romain-P** [azerothcore/Keira3#1040]
Would a ssh tunnel support be conceivable in the future? My mysql ports are not exposed

**Comment by Helias** [comment]
duplicate of https://github.com/azerothcore/Keira3/issues/93

Anyways, for now, you can follow this guide to make the ssh tunnel https://www.linode.com/docs/databases/mysql/create-an-ssh-tunnel-for-mysql-remote-access/
If we will can, we will support it natively from Keira3
