### ISSUE TITLE
Updating anything in Creature Template adds on extra line

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/Keira3#1074]
Updating anything in Creature Template adds on an extra line in the 'Diff-query' and trying to run it results in error.

Example of Keira3 query when updating faction: 
```
UPDATE `creature_template` SET `faction` = 35, `spell_school_immune_mask` = 'undefined' WHERE (`entry` = 582);
```
Example of what it should be when updating faction:
```
UPDATE `creature_template` SET `faction` = 35 WHERE (`entry` = 582);
```

**Comment by 55Honey** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/4358/files

Is it related to the new column added here?

**Comment by Voxstrasza** [comment]
Possibly.  Keira hasn't updated with the new line in creature_table it seems.

@Kitzunu why did you break it? 😠

**Comment by Helias** [comment]
Hehe, kitzunu already created a PR lot time ago for this,but we need to finish it 😅

Unfortunately, I am very busy in this period and I didn't finish it

**Comment by FrancescoBorzi** [comment]
@Kitzunu can't we just add that new field in `creature_template` to make Keira3 work with latest AC master ? I guess we don't need to do everything at once

**Comment by Kitzunu** [comment]
I dont have time atm. But anyone can just copy that part from the open pr

**Comment by Kitzunu** [comment]
feel free to test the PR
