### ISSUE TITLE
[Feature Request] Add tables for npc_text, creature_text, gossip etc

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/Keira3#1078]
Considering AC is missing quite a few NPC gossip and text, it would be worth to add these tables to Keira3 in order to rectify those text issues quicker.

**Comment by The-GhostRider** [comment]
> Considering AC is missing quite a few NPC gossip and text, it would be worth to add these tables to Keira3 in order to rectify those text issues quicker.

Yes, I totally agree, they are fundamental tables, and in my opinion they were needed from the start, above all because the "creature_text" "gossip" etc... tables are often used in SAI, therefore due to this close correlation, it is crucial to have these tables in Keira.

**Comment by FrancescoBorzi** [comment]
Comment from @Annamaria-CC:

creature_text able to search and add lines to creatures
broadcast_text able to search up

**Comment by FrancescoBorzi** [comment]
Comment from @Gultask:

A creature_text Editor (coupled with a broadcast_text browser) is one of the main improvements I can think of at this time.

A broadcast_text browser in my mind is something simple that allows me to see all entries within a range or filtered for male_text/female_text

I always end up using the same queries when I want to search for entries. Then after finding the ID, I usually go to the Data section and see what's adjacent so I don't miss anything relevant.
```
SELECT * FROM `broadcast_text` WHERE `MaleText` LIKE '%I must feed%' OR `FemaleText` LIKE '%I must feed%';
```
