### ISSUE TITLE
One-time login. Remember me

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/Keira3#1215]
Would be nice to just auto login. To save time :D

**Comment by willkillson** [comment]
This will be my next tasker. 👍

**Comment by willkillson** [comment]
@Kitzunu Would it be fine for this information to just be saved instead of hardcoded (very similar to what I did with the screen size/position)? Or do you want an options in a drop down in the title bar that skips this prompt all together?

**Comment by Kitzunu** [comment]
I have used some other tools that automatically logs you in after you have logged in once, until you actually hit the logout button. That's kind of how I was thinking

**Comment by willkillson** [comment]
So here we have the verbiage "Connect"
![image](https://user-images.githubusercontent.com/26101774/119739896-ce62eb00-be37-11eb-8979-c8e78d00840f.png)

, but once the terminology changes to "Logout"
![image](https://user-images.githubusercontent.com/26101774/119739929-da4ead00-be37-11eb-8bb1-a183f47a5b25.png)

Would it be fine to change the name from "Logout" to "Disconnect", and maybe change the icon to something more akin to that?  

The other way to think about this would be to change "Connect" to "Sign in", that would then make it consistent.

**Comment by FrancescoBorzi** [comment]
@willkillson now that you made me notice that, it makes perfect sense :)

I'd go for replacing `Logout` with `Disconnect`

**Comment by Kitzunu** [comment]
Agree
