### ISSUE TITLE
Can't connect to AzerothCore DB

### ISSUE THREAD

**Issue by yaserOSource** [azerothcore/Keira3#1218]
I can connect via HeidiSQL but not via Keira3

If you run azerothcore with docker and try to connect to the db with keira it wont work

**Comment by Helias** [comment]
what is the error that you get?

**Comment by lucahost** [comment]
I'm facing the same issue. The error is ER_NOT_SUPPORTED_AUTH_MODE

![image](https://user-images.githubusercontent.com/5907956/120939518-bb45fa00-c718-11eb-9f2b-b0501576e181.png)
