### ISSUE TITLE
wrong label on SMART_EVENT_FRIENDLY_MISSING_BUFF

### ISSUE THREAD

**Issue by Krejza9** [azerothcore/Keira3#1286]
![image](https://user-images.githubusercontent.com/5585555/120890869-b0e70b80-c605-11eb-81f7-8210d656d89e.png)

It says to set a negative value, but this is not possible because the column **event_param*** on AC is **Unsigned** and cannot be set to negative values

**Comment by FrancescoBorzi** [comment]
@Krejza9 those strings are in `src/app/shared/modules/sai-editor/constants/sai-event.ts`

feel free to send a PR with the proper text ;)

**Comment by Krejza9** [comment]
As you wish :-D 
#1294
