### ISSUE TITLE
Keira3-3.2 and Mysql 8.0 

### ISSUE THREAD

**Issue by admdbreno** [azerothcore/Keira3#1327]
Good morning, I am encountering the following problem when connecting Keira3-3.2.exe Windows:
Error: Client does not support authentication protocol requested by server; consider upgrading MySQL client
Code: ER_NOT_SUPPORTED_AUTH_MODE
Error: 1251
SQL State: 08004
my MySQL version is 8.0
#could someone help me about this error...?

**Comment by Helias** [comment]
https://stackoverflow.com/questions/65271160/er-not-supported-auth-mode-issue-with-keira3

**Comment by admdbreno** [comment]
sorry to ask, but I'm adding the following command described in the answer, inside MySQL 8.o Command Line Client ... but I'm not getting the authentication ... help me please?

**Comment by Helias** [comment]
try to restart the mysql service after running that query and try again

**Comment by admdbreno** [comment]
I was not successful, I sent you a message on discord, my profile is lipe#6279

**Comment by grimdeathr** [comment]
same issue here. Is this due to mysql 8?

**Comment by Helias** [comment]
kind of, actually it's caused by a new authentication protocol  that is not supported by the mysql js library, so to fix it you have to change it from mysql and use another protocol for authentication.

**Comment by grimdeathr** [comment]
azerothcore by default uses sql 8 i think, at least with docker thats what i get

**Comment by grimdeathr** [comment]
`ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';`

So I would run this on the mysql cli?
