### ISSUE TITLE
Bug on Creature Template

### ISSUE THREAD

**Issue by wizzymore** [azerothcore/Keira3#1404]
If you modify anything on Creature Template you get 2 values with undefined:
```sql
UPDATE `creature_template` SET `detection_range` = 'undefined', `ExperienceModifier` = 'undefined' WHERE (`entry` = 9236);
```
What i modified was unit_class from 2 to 3, and these two changes appeared, i switched it back to 2 so the diff query should show nothing now, and they are still shown.

I use version 3.2.0

**Comment by Asthalor** [comment]
So far on the development build at least the detection_range thing is fixed. On the 3.2.0 version used by everyone the changes are still not merged.
The experience modifier is still popping even on the latest build, so we should add the field to the Creature Template to fix that when the build is pushed.
