### ISSUE TITLE
Wrong values for reputation reward appear on the GUI 

### ISSUE THREAD

**Issue by baranzadeoglu** [azerothcore/Keira3#1426]
This is how reputation reward works (from Wiki);
"
RewardFactionValueId1

This field is used for reputation lookup in QuestFactionReward.dbc if quest_template#RewardFactionValueId is 0. Value X in this field indicates RepX column of QuestFactionReward.dbc. If RewardRepValueId is positive, reputation from the first row of QuestFactionReward.dbc will be used, for negative values the second row is used.
"

So for a normal quest that rewards reputation, the value for RewardFactionValueId1 is from 1 to 10 which is cross referenced to another database (QuestFactionReward.dbc) from which the appropriate final reward value is derived.

However Keira3 GUI currently prints the value of RewardFactionValueId1 rather than its corresponding actual reward value in QuestFactionReward.dbc.

See an example of this issue in my comment:
https://github.com/azerothcore/azerothcore-wotlk/issues/7273

**Comment by Helias** [comment]
closed by https://github.com/azerothcore/Keira3/pull/2680
there is still a bug to fix reported here https://github.com/azerothcore/Keira3/issues/2681
