### ISSUE TITLE
creature_template extra flags are not displayed properly.

### ISSUE THREAD

**Issue by patou01** [azerothcore/Keira3#1493]
Sorry hit enter too fast.
in Keira:
![image](https://user-images.githubusercontent.com/2592673/137597928-2c6499a8-c884-4e32-991f-4f17f952c98b.png)

In Wiki:
![image](https://user-images.githubusercontent.com/2592673/137597960-558fdf5e-35bf-4b78-b6ad-7ae4ee2b3709.png)

In code:
![image](https://user-images.githubusercontent.com/2592673/137597979-bd7acc59-aad4-4990-aaf8-3551c0eed566.png)
Code is dated from this change:
https://github.com/azerothcore/azerothcore-wotlk/commit/e29acf44d03793f4f12193dd0f7622ea5ddf6938#diff-2222cde2ff898034f0ce38bba2d5755cbdeef050c328b2d56599bc6d6664afc1

**Comment by FrancescoBorzi** [comment]
fixed by https://github.com/azerothcore/Keira3/pull/1622
