### ISSUE TITLE
Would this be possible to make in Keira3?

### ISSUE THREAD

**Issue by Sulan2** [azerothcore/Keira3#1504]
Im trying to create a NPC that is mounted during combat and then dismounts at a certain %.
In type_flags there is 11: 2048 Allow mount in combat but in smartAI there is now way to remove it?

I dont know how this works but would it be possible to add this as a feature or can u move the allow mount part into another _flag like unit_flags because everything else is basicaly adjustable in SmartAI?

**Comment by Helias** [comment]
This is more a question about capability of Conditions/SAI, it's not an issue of the Keira3 software.
