### ISSUE TITLE
RewardMoneyDifficulty = 'undefined' in `quest_template`

### ISSUE THREAD

**Issue by Meramaf** [azerothcore/Keira3#1516]
`RewardMoneyDifficulty` = 'undefined' in  `quest_template` With last AzerothCore.

Keira version: 3.3.0

AC Latest 

![C2182558-8E25-42EF-8A64-84FCE2C95AB6](https://user-images.githubusercontent.com/76571216/139251072-96929991-ffd3-4876-8b54-6be8b2b12695.png)

I think after this commit:

https://github.com/azerothcore/azerothcore-wotlk/commit/1fb6830b15617d9f2429ff5f4760120fc6c4d085

**Comment by Shineslippers** [comment]
Issue is still there
![image](https://user-images.githubusercontent.com/85256266/145679931-49ed66a9-0542-4e63-b922-d6f00743b237.png)

**Comment by Helias** [comment]
we need to release the new version of Keira3, to get this fix for now you need to build the software from the source code
