### ISSUE TITLE
[bug] can't display game object loot

### ISSUE THREAD

**Issue by baranzadeoglu** [azerothcore/Keira3#1518]
![image](https://user-images.githubusercontent.com/84640316/139742171-f82bfcd6-9750-4570-8c11-a0129d57c8c5.png)

**Comment by Helias** [comment]
As written, you need to associate to the `Data1 (lootid)` field the `entry` in `gameobject_loot_template` and `type` 3 or 25

**Comment by FrancescoBorzi** [comment]
@baranzadeoglu this is not a bug, you need to do what the info message is telling
