### ISSUE TITLE
[Feature Request] SSH Connection

### ISSUE THREAD

**Issue by ObscenityIB** [azerothcore/Keira3#1525]
Since for security, mysql by default denies remote access, and you also have to open the port to the world first.
Im using a SSH tunnel to forward 3306 to my remote server, so it thinks its a local connection and its not exposed to the world.

Adding SSH support with key authentication as a bonus to the login screen would get around the security issue.

Only other option is installing an x window system on the remote machine and connecting to the x server to, very slowly, display the kiera window remotely.

**Comment by Helias** [comment]
thanks for the suggestion but this is a duplicate of https://github.com/azerothcore/Keira3/issues/93

**Comment by ObscenityIB** [comment]
Ah I didn't see that one.
