### ISSUE TITLE
Must be added to SmartScripts

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/Keira3#1607]
#### Do not close this issue, i will add more smartscript in the future.

# List
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/10018
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/10019
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/9994
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/9993
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/9979
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/9967
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/9772
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/10037
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/10053
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/10054
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/10210
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/10231
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/10254
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/10255
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/10286
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/14371

**Comment by Gultask** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/14811

**Comment by avarishd** [comment]
Stuff above have been added, only missing comment generation for them now.

**Comment by Gultask** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/16254

**Comment by Nefertumm** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/16411

**Comment by Helias** [comment]
is everything has been added? anything missing?

**Comment by Gultask** [comment]
I completely forgot to add SMART_TARGETS in the last PR
Also comments need reorganizing. I'll see what I can do this week

**Comment by Helias** [comment]
the last ones have been added by https://github.com/azerothcore/Keira3/pull/2347/, thanks @Gultask
