### ISSUE TITLE
Missing speed_swim and speed_flight fields in creature editor

### ISSUE THREAD

**Issue by bronzato** [azerothcore/Keira3#1615]
The actual version of Azeroth core has speed_swim and speed_flight fields in creature_template table in World Database.
Keira need have this fields in creature editor too.

![image](https://user-images.githubusercontent.com/6419694/148874539-c422ee94-dddd-4960-b8b0-34c292883cf7.png)

**Comment by Helias** [comment]
Thanks for the report, we'll surely add this into the next release
