### ISSUE TITLE
SQL error while entering creature spawn section

### ISSUE THREAD

**Issue by nolt** [azerothcore/Keira3#1634]
Can't view creature spawn. When I search creature, click on it and go to spawn section Keira prints this error:
↓↓↓

```
Error:    Unknown column 'id' in 'where clause'
Code:    ER_BAD_FIELD_ERROR
Errno:    1054
SQL State:    42S22
```

**Comment by Helias** [comment]
Which Keira3 version and AC version are you using?

**Comment by Helias** [comment]
this is the breaking change PR https://github.com/azerothcore/azerothcore-wotlk/pull/10169
I am making compatible Keira3 now

**Comment by Helias** [comment]
fixed ;-)

soon we will release new binaries, if you can't wait you can build yourself the binary of the PR

**Comment by Tntdruid** [comment]
I'm getting this too now whit Keira Version: 3.10.5
