### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/Keira3#1639]
## List

- [] https://github.com/azerothcore/azerothcore-wotlk/pull/10287
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/10298
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/10299
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/10300
- [] https://github.com/azerothcore/azerothcore-wotlk/pull/10332

**Comment by Helias** [comment]
We already have these conditions except `CONDITION_DIFFICULTY_ID`
