### ISSUE TITLE
Creature_template dont have "InhabitType" Column

### ISSUE THREAD

**Issue by LordArcanine** [azerothcore/Keira3#1656]
![image](https://user-images.githubusercontent.com/3597399/151909190-eb8669ab-fd86-46ce-9537-002d3e404545.png)

Creature_template dont have "InhabitType" Column

**Comment by Helias** [comment]
thanks for your report, I think we already fixed this, but we need to make another release.

**Comment by FrancescoBorzi** [comment]
it's fine on latest master, the next release will fix this.
