### ISSUE TITLE
No item preview display

### ISSUE THREAD

**Issue by Alehelm** [azerothcore/Keira3#1665]
Upon recent download again I'm experiencing no item preview on the left-hand side, any known cause for this?
Items still update, etc in database fine

![New Project](https://user-images.githubusercontent.com/98996636/152628922-e8937567-4cb0-4596-8851-5c646a5dfaac.png)

**Comment by duncrafter** [comment]
I've encountered this error too, maybe next release will fix it?

**Comment by Alehelm** [comment]
> I've encountered this error too, maybe next release will fix it?

Ok, thanks, good to know it may not be my config causing the issue. Will wait and see for next release
