### ISSUE TITLE
Sidebar icons have something wrong

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/Keira3#1695]
on macOS you can see some squares instead of the icons

**Comment by buddiman** [comment]
Possibly related?
![image](https://user-images.githubusercontent.com/10009755/153761563-972e41ab-7bb9-4b86-bbc1-ed78c9ed0678.png)

The squares where the arrows should be even have the correct animation:
![Arrow](https://user-images.githubusercontent.com/10009755/153761649-0a49c69d-b801-4bf8-8b1c-3bb99c5c2d67.gif)

Is it the same visual bug? I'm using the latest Windows release.

**Comment by FrancescoBorzi** [comment]
@buddiman yes
