### ISSUE TITLE
Just 2 minor "tooltip fix" things in Keira

### ISSUE THREAD

**Issue by Sulan2** [azerothcore/Keira3#1696]
Hey I use this program a lot just wanted to thank everyone who made it

Got 2 things Ive noticed which is very minor but thought id share anyway

1. In SmartAI editor, at Target -> 19 Closest creature -> Must Be Dead, the info text about it says the same thing.
(if set to 0 it will only target alive targets, if set to 1 it will only target alive targets)

2. On creature template -> Type_flags -> 4 Boss mob I just had some more info about
It also means the NPC will deals full damage to the player no matter what level the player is and doesnt have any higher chances of missing attacks
For example a NPC with this flag and is lvl 20 will have the same chance of hitting the player target if the player was lvl 20 or level 80
A higher level player will only resist abit more % of spells 

(Always deal full damage, always same chance to hit attacks) could be in the description if there is room

**Comment by Helias** [comment]
Implemented, thank you @Sulan2
