### ISSUE TITLE
Some thoughts on SmartAI Editor - Event 102 Near Players Negation

### ISSUE THREAD

**Issue by Sulan2** [azerothcore/Keira3#1705]
I feel like the info text on this event isnt really clear/ is wrong

I created a NPC in SmartAi editor that, when NO players are in range it will trigger the event function
In order to make this work in game, Event is 102 Near Players Negation and Maxplayers is set to 1

However  the info on maxplayers says the value choosen is = whats needed to trigger the event
Which means if I set the value of maxplayers to 1 the event should trigger if 1 player is close

But shouldnt the info on Maxplayers read "Amount of players needed for the event to NOT trigger"? because thats how it works in game
Setting maxplayers at 1 will make it so that 1 player in range will STOP the event from happening

The way both events 101 and 102 are worded now feels like they are doing the same thing but I think the 102 event arent inversed in a maxplayer/minplayers kind of way
instead 102 is the amount of players needed for an action to NOT happen
101 is the amount of players needed for an action to happen

**Comment by FrancescoBorzi** [comment]
@Sulan2 would you like to open a PR to improve this text?

**Comment by Sulan2** [comment]
> @Sulan2 would you like to open a PR to improve this text?

I dont know what that means
U mean I can edit the text in Keira3 myself?

**Comment by Sulan2** [comment]
I would love to help edit some tooltips if u wanna tell me how I can help

**Comment by FrancescoBorzi** [comment]
@Sulan2 if you want to contribute to Keira3, this is your starting point:

https://www.azerothcore.org/wiki/keira3-internals

**Comment by FrancescoBorzi** [comment]
@Sulan2 however, to edit tooltips is fairly easy and you don't need to know all the stuff mentioned in the above article, just have a look at the source code and see how existing tooltips are made

**Comment by Sulan2** [comment]
> @Sulan2 however, to edit tooltips is fairly easy and you don't need to know all the stuff mentioned in the above article, just have a look at the source code and see how existing tooltips are made

I dont know anything about code but I downloaded source looked around abit and found sai-event.ts which has some of this info. Im supposed to change it here and then send the file to you?

**Comment by FrancescoBorzi** [comment]
> > @Sulan2 however, to edit tooltips is fairly easy and you don't need to know all the stuff mentioned in the above article, just have a look at the source code and see how existing tooltips are made
> 
> I dont know anything about code but I downloaded source looked around abit and found sai-event.ts which has some of this info. I can change it here and then send the file to you?

@Sulan2 better if you try to run Keira3 in development mode (see the README.md) so you can test your changes before submitting the code

**Comment by Sulan2** [comment]
> > > @Sulan2 however, to edit tooltips is fairly easy and you don't need to know all the stuff mentioned in the above article, just have a look at the source code and see how existing tooltips are made
> > 
> > 
> > I dont know anything about code but I downloaded source looked around abit and found sai-event.ts which has some of this info. I can change it here and then send the file to you?
> 
> @Sulan2 better if you try to run Keira3 in development mode (see the README.md) so you can test your changes before submitting the code

I appreciate the info but I just dont have any code kind of experience so I cant even make sense of the readme on how to run keira in development mode.
I can write a text on what tooltips I think should be changed but someone else will need to put it into the actual app I guess

**Comment by FrancescoBorzi** [comment]
>  I can write a text on what tooltips I think should be changed

@Sulan2 ok, please do

**Comment by Helias** [comment]
implemented, thanks @Sulan2 !

**Comment by Helias** [comment]
re-implemented for https://github.com/azerothcore/Keira3/issues/1741
so this issue is a duplicate
