### ISSUE TITLE
Sulans list of some tooltip changes for Keira3(Last updated 20 January 2023)

### ISSUE THREAD

**Issue by Sulan2** [azerothcore/Keira3#1741]
I will update this post if I find something in the future

SmartAI Editor

Event -> 102 Near Player Negation
The I Icon next to Near_Player_Negation should say
"Amount of players needed within a range to STOP the action"

Param 1 (maxPlayers) should be called "Amount of Players" and the I icon should say "Players needed to STOP the Action"

Event -> 101 Near Player
The I Icon next to Near_Players should say
"Amount of Players needed within a range to Start the action"

Param 1 (minPlayers) should be called "Amount of Players" and the I icon should say "Players needed to Start the Action"

Action -> 69 MOVE_TO_POS 
Param 3 (isControlled)
The I icon should say
"0 = aggro/threat will make it focus on player instead"
"1 = Fixated to run to the xyzo position no matter what"

Target -> 5 Hostile Random
Param 1 2 and 3 have a meaning here (The world server says it)
Param 2 is "Player Only" Boolean 0 or 1
Param 1 and 3 I dont know what they do however but a guess is that one of em is about distance

Edit: (All target Hostile seem to use this, Param 2 for target Hostile 3 4 5 6 are all player only boolean)

Target -> 19 Closest Creature
The I Icon for MustBeDead
This is just a tooltip error currently using 1 for both. I dont know what value of 0 or 1 correlated to what here

----------------------------------
Creature Template

Type_flags -> BOSS_MOB

The description here should say
"Hidden level in Creature Portrait (Shown as ??) Immune to Knockback. Always deal full damage to players, doesnt miss spells."

Type -> 9 Mechanical
This doesnt have any description for anything, maybe its not such a big deal but u can add 
"(cannot be healed by healing spells)" here to Mechanical if u want

-------
Item Template

Spell -> Trigger_1_2_3_4_5
These could have an I icon that says
0 = Use, uses Charges and cooldown below
1 = Equip, uses Cooldown Column in spell_proc_event table database
2 = Chance on Hit, uses ppmrate and cooldown below
5 = Having this item in your bag or equipped will also trigger an aura on you.

**Comment by Sulan2** [comment]
On this site https://www.azerothcore.org/wiki/smart_scripts

It has flag values and meaning for Castflags and Summon Type, wouldnt it be possible to get them into Keira3 directly?

In SmartAI Editor 
Action -> 11 Cast -> CastFlags

1 | Interrupt any spell casting
2 | Triggered (this makes spell cost zero mana and have no cast time)
32 | Only casts the spell if the target does not have an aura from the spell
64 | Prevent combat movement on cast, allow on fail range, mana, LOS


Action -> 12 Summon Creature -> Param 2 (SummonType)
(This doesnt have any I icon yet)

1 | Despawns after a specified time OR when the creature disappears.
2 | Despawns after a specified time OR when the creature dies.
3 | Despawns after a specified time.
4 | Despawns after a specified time after the creature is out of combat.
5 | Despawns instantly after death.
6 | Despawns after a specified time after death.
7 | Despawns when the creature disappears.
8 | Despawns when UnSummon() (or Force Despawn action) is called.

**Comment by Helias** [comment]
this last issue that is related to acore, can be related to this https://github.com/azerothcore/azerothcore-wotlk/issues/5270. ?

**Comment by Sulan2** [comment]
> this last issue that is related to acore, can be related to this [azerothcore/azerothcore-wotlk#5270](https://github.com/azerothcore/azerothcore-wotlk/issues/5270). ?

Yeah I guess, I dont know how the techical behind all this works.
With this said, I think 7 Action Invoker is the perfect Target for this Event and since 14 and 74 are basicaly the same thing its prety wierd that 7 Action Invoker only works on 1 of them

**Comment by Sulan2** [comment]
@Helias 

Target - >GAMEOBJECT_DISTANCE AND GAMEOBJECT_RANGE

This target settings acctualy targets all Gob IDs within a range and therefor the I Icon should say 
"Target ALL gameobjects of a given entry withing a given distance"

Also these 2 does the same thing, why would there need to be 2 versions of this?
Gameobject_Distance should be removed and Param 4 on Gameobject_Range should be a Limit Target param that lets u decide how many to trigger

-------

Event -> 64 GOSSIP_HELLO
Param 1 can have a value, I have no idea what it does but it doesnt seem to be a boolean 0 1 value either
It has something to do with how many times u want something to happen

-------

Action -> 97 JUMP_TO_POS

This action doesnt work with SMART_TARGET_POSTION, it works with SMART_TARGET_SELF

The I icon should say
"Makes the NPC jump to a given position with a given speed. Must use SMART_TARGET_SELF with this action_type. 
If Selfjump is set to 0 = The Target XYZO Params is location of where to Jump
A speed value around 12 is normal speed"

Self Jump 1, I have no idea why it even needs to exist and I cant make sense of it

Action -> 53 WP_START
The I Icon for Param 5 DespawnTime should ALSO say "0 = will not despawn"

Action -> 60 SET_FLY

Param 2 = Speed
Param 3 = Disable Gravity boolean 0/1 where 1 = enabled 0 = disabled

Action -> 89 Random Move
The I Icon should also say "(Only works outside of combat)"

Action -> 38 SET_IN_COMBAT_WITH_ZONE

This action should more be called SET_IN_COMBAT_WITH_PLAYER because it doesnt set NPCs in combat with other NPCs

----------

Creature -> Vendor -> maxcount
The I Icon should also say (if choosing a value of 1 or higher also requires incrtime value to work)

Creature Template -> Unit_flags -> 25 Not Selectable

The info text should say, "No name text shown, no nameplate shown and can’t be selected by mouse or with /target {name} command.

Creature Template -> DamageModifier

The I Icon should say 
"Increases auto attack damage and damage from spells or abilities that deals WEAPON based damage"

Creature Template -> Unit_Flags -> 1 Non_Attackable, 7 Not_Attackable and 16 UNK_16 - No Attack 2 

All of these does the same thing, not sure why there needs to be 3 versions
Description should say - Cannot be attacked by Players or NPCs but can still attack players

Creature -> Spawn -> Equipment_id
An I Icon here could say, 1 = uses the info set in equipment template  0 = no weapons equipped

Creature Template -> ArmorModifier

An I Icon here could say 
Damage taken from physical attacks, a value of 1 is normal
Values under 1 mean it will take more damage
Values over 1 mean it will take less damage

**Comment by Helias** [comment]
Thanks @Sulan2 , unfortunately I do not have a lot of time to improve/fix these things, but the first step to make this, it's writing a detailed issue, that is what you did, now we need a developer that can apply these reports to Keira3

**Comment by Sulan2** [comment]
> Thanks @Sulan2 , unfortunately I do not have a lot of time to improve/fix these things, but the first step to make this, it's writing a detailed issue, that is what you did, now we need a developer that can apply these reports to Keira3

I see, I just love the program so trying to do what I can to help. I dont see how anyone could create a good WoW server without this program. If u somehow made it easier to edit things into the program I could do it myself

**Comment by Sulan2** [comment]
Target -> 201 Player_with_aura -> Param 3 distMax

There should be an I icon here that says
"This needs to have a value of 1 or higher, or it will not work"

------------------------------------

Event -> 70 RESPAWN TARGET

The i icon for this should remove "Only works for gameobject target"
and add
"Also works for creatures if target used is 12 Stored"

Event -> 2 and 3 HEALTH_PCT/MANA_PCT

The I icon here should include
"This event only works if the NPC is in combat"

MinHealth% I Icon should say "Lowest amount of health in % for the action to trigger"
MaxHealth% I Icon should say "Highest amount of health in % for the action to trigger"

MinMana% I Icon should say "Lowest amount of mana in % for the action to trigger"
MaxMana% I Icon should say "Highest amount of mana in % for the action to trigger"

------------------------------------------

Action -> 89 Random Move

This action doesnt only happen once even if u have a Event that triggers it without any repeat values set.
Therefor the I Icon for Random_Move should say
"Creature moves to random positions in a given radius (Only works when its not in combat)

Action -> 63 Set_Counter

You could add a ( ) box here that says. 
The values set here can stack together compared to in Set Data.
If u want for example 1 door to open after having used 2 objects in random order then set Action 63 1 1 and on the objects and Event 77 Counter set 1 2 on the door

Action -> 47 SET_VISIBILITY

the I icon here includes gameobject but I have never managed to make it work on gameobjects.
Dont know if this might be a core problem

Action -> 90 Unit Field Bytes, 91 Remove Unit Field bytes and 204 Set Unit Movement Flags.

In the I Icon for these there could be a link to this page 
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Unit/Unit.h

The info for all of em are on that page.

Action -> 63 Set_Counter

Param 3 Reset.
I think this is acctualy Repeat, like if u want it to be able to happen multiple times during the same encounter.

---------------

Creature Template -> PetSpellDataId

The I icon here should say 
"If the value here is 0 and its a summoned pet, then it uses spells from creature_template_spell"
"If u have set values in both then a value above 0 here will overide template_spell"


Creature -> Template Addon - Auras

This doesnt work when u type it like 8482-7473-8583
it works when u type it like 8482 7473 8583

Therefor should not be "comma separated" and instead "spacebar separated"

------------------
Gameobject Template -> Type 22 -> Spell

The I Icon here should also say
"If the spell is a teleport spell, also needs info set in spell_target_position table in world DB"

**Comment by Helias** [comment]
`Target -> 5 Hostile Random`, not clear to me
`Target -> 19 Closest Creature` already handled for this issue https://github.com/azerothcore/Keira3/issues/1696
`Type_flags -> BOSS_MOB` already handled for this issue https://github.com/azerothcore/Keira3/issues/1696
`Type -> 9 Mechanical` :heavy_check_mark: 
`Spell -> Trigger_1_2_3_4_5` I already improved it in another PR for another issue, I do not know where I can put the description you wrote

(I will continue later, thanks!)

**Comment by Helias** [comment]
`Action -> 11 Cast -> CastFlags` :heavy_check_mark: 
`Action -> 12 Summon Creature -> Param 2 (SummonType)` :heavy_check_mark: 
`Another thing, even tho I dont think this first one is a Keira3 thing and maybe more of ACore problem` this is acore related (I mean the health events)
`Event 14 Friendly_Health tooltips`  :heavy_check_mark: 
`Target - >GAMEOBJECT_DISTANCE AND GAMEOBJECT_RANGE` I have no idea if they are the same but I think that the current description is good enough.
`Event -> 64 GOSSIP_HELLO - Param 1 can have a value,` no one is saying the opposite, there is no tooltip about it
`Action -> 97 JUMP_TO_POS` improved but I left the 1 option  :heavy_check_mark: 
`Action -> 53 WP_START` :heavy_check_mark: 
`Action -> 60 SET_FLY` :heavy_check_mark: 
`Action -> 38 SET_IN_COMBAT_WITH_ZONE` I would not change the name, moreover, it does not depend on Keira3, but I updated the description.  :heavy_check_mark:

**Comment by Helias** [comment]
`Event -> 70 RESPAWN TARGET` ~Event~ Action  :heavy_check_mark:
`Event -> 2 and 3 HEALTH_PCT/MANA_PCT` :heavy_check_mark:
`Action -> 89 Random Move` :heavy_check_mark: (you wrote this twice hehe)
`Action -> 63 Set_Counter` :heavy_check_mark: 
`Action -> 47 SET_VISIBILITY` I do no think that Keira3 is responsible of this
`Action -> 90 Unit Field Bytes, 91 Remove Unit Field bytes and 204 Set Unit Movement Flags.`  :heavy_check_mark: 
`Action -> 63 Set_Counter param 3` not sure, I left as it is.
`Creature Template -> PetSpellDataId` :heavy_check_mark: 
`Creature -> Template Addon - Auras` :heavy_check_mark: 
`Gameobject Template -> Type 22 -> Spell`  :heavy_check_mark:

**Comment by Helias** [comment]
done on https://github.com/azerothcore/Keira3/pull/2157

**Comment by Sulan2** [comment]
Just wanted to say thanks a lot helias, great work and thanks for adding my text changes

About Hostile Random, the 3 first Params have a meaning and could have a text instead of being called Param

Param 2 is Player Only 1 or 0 value
I think Param 3 is range/distance but cannot say for sure

**Comment by Helias** [comment]
we only have to put "sure" things, anyways, create a separate issue for it

**Comment by Sulan2** [comment]
![Param2](https://user-images.githubusercontent.com/86251944/222482327-bb3e6197-28b9-444d-a4bc-dac821339936.PNG)

**Comment by Helias** [comment]
interesting, create an issue with these screenshot and details, thanks 👍

**Comment by Sulan2** [comment]
Param 1 is Distance, just tried it in detail. If its 0 then it uses the range of the spell in spell.dbc otherwise if u set for example 10 then it will not shoot a 40yard spell on anyone further than 10yards etc

**Comment by Helias** [comment]
wrap everything into a new issue to keep track of this and not loose this report, this issue is already closed, it's better to do single issues with single reports and small to keep track of them

anyways, thanks 👍
