### ISSUE TITLE
How does SmartAI Action 97 JUMP_TO_POS Work?

### ISSUE THREAD

**Issue by Sulan2** [azerothcore/Keira3#1772]
This is one of those action I havent managed to make work yet.
The I Icon have a pretty good explanation of it but I dunno, nothing happens in game
tried Disabled gravity aswell etc if that matters

is there any more info on this? The info given at the I Icon seems like who ever wrote it know how this Action works

**Comment by Helias** [comment]
did you check the wiki? https://www.azerothcore.org/wiki/smart_scripts

**Comment by Sulan2** [comment]
> did you check the wiki? https://www.azerothcore.org/wiki/smart_scripts

The info there is basicaly the info already in Keira3

With that said, I got it to work now and it doesnt work with SMART_TARGET_POSTION as stated in Keira3, it works with SMART_TARGET_SELF

**Comment by Helias** [comment]
ok, I am updating the wiki then, anyways keira3 use that wiki to show you the info
I'll update it, thanks

I don't know exactly each compatibility of each combinations of SAI, so I am happy that you figured out how to make it work

**Comment by Sulan2** [comment]
ill add some tooltip changes for it in my other post when I updated it at some point in the future

**Comment by Helias** [comment]
ok, thank you!
