### ISSUE TITLE
smartAI: generate comments on eventype 61 causes link arugment to be 1

### ISSUE THREAD

**Issue by Samsequel** [azerothcore/Keira3#1820]
If you generate comments on eventype 61 (link), the argument param1 will become 1, which is false and will make it not run and cause errors. It should not add a 1 in param1. (should be 0)
![image](https://user-images.githubusercontent.com/20357406/174559187-6b818fbd-6efb-48c7-92e5-f4e64931e2f9.png)

**Comment by pangolp** [comment]
I don't quite understand the problem, but let's see if that's what I think. You generate a new record, inside `smart_scripts`, whose `event_type`, is 61 (link) and the parameters are set to 0. But when you edit it, and add a comment to the record, then it makes one of the parameters, change to zero? Or am I misunderstanding?

**Comment by temperrr** [comment]
when you press generate comments, it takes the values from the linked event .

**Comment by pangolp** [comment]
I have not been able to reproduce the error.
I must be doing something wrong.
![image](https://user-images.githubusercontent.com/2810187/186194174-623097ce-ab55-4a3c-97af-11cdba319f9a.png)

**Comment by temperrr** [comment]
![image](https://user-images.githubusercontent.com/20357406/186231932-5b9a2a6d-e794-4c03-b1c4-e700f24e7d86.png)
Pressing on
![image](https://user-images.githubusercontent.com/20357406/186231963-c256c107-7a81-4c20-a6e3-7321a4f9c512.png)
generates
![image](https://user-images.githubusercontent.com/20357406/186232206-3768d831-f3bd-41d2-bfa5-c06b2e1b1e16.png)
But only if 
![image](https://user-images.githubusercontent.com/20357406/186232228-601ef2b3-01f0-4a50-a6e8-8af5a82f464d.png)

has any info (2 I added just now to show the bug, normally its 0)

**Comment by pangolp** [comment]
Thanks for the explanation and the example, because I could not replicate the problem.

**Comment by Gultask** [comment]
Yeah this is pretty annoying when working with several LINKs, I have to clean up the event parameters every time after I generate comments
