### ISSUE TITLE
Keira-3.4.2.WINDOWS.zip Contains Mac

### ISSUE THREAD

**Issue by DavuKnight** [azerothcore/Keira3#1893]
Just Downloaded and unzipped [Keira-3.4.2.WINDOWS.zip](https://github.com/azerothcore/Keira3/releases/download/v3.4.2/Keira-3.4.2.WINDOWS.zip)
It Has 
![image](https://user-images.githubusercontent.com/112143769/187563826-2b4999b8-b59b-4b6d-8eba-c86815bef2ac.png)
Inside

**Comment by nsaccente** [comment]
Came here to say this. Can confirm

**Comment by XSNomad** [comment]
Confirmed as well.

**Comment by Awixs777** [comment]
Confirmed

**Comment by Helias** [comment]
fixed, sorry for this issue
