### ISSUE TITLE
Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by mehdikhody** [azerothcore/Keira3#2049]
Hi, I installed the latest acore version on my ubuntu server and I can connect to database with HeidiSQL but I cant do it with Keira3.

```
Host: xx.xxx.xxx.xx
Port: 3306
Username: acore
password: acore
Database: acore_world
```

```
Error: Client does not support authentication protocol requested by server; consider upgrading MySQL client
Code: ER_NOT_SUPPORTED_AUTH_MODE
Errno: 1251
SQL State: 08004
```

**Comment by niugm** [comment]
Execute the following query in MYSQL Workbench

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';

Where root as your user localhost as your URL and password as your password

Then run this query to refresh privileges:

flush privileges;

Try connecting using node after you do so.

If that doesn't work, try it without @'localhost' part.

**Comment by FrancescoBorzi** [comment]
this bug has been solved but we still need to release a new Keira version with it
