### ISSUE TITLE
Information Tooltip doesnt show info

### ISSUE THREAD

**Issue by Samsequel** [azerothcore/Keira3#2067]
![image](https://user-images.githubusercontent.com/20357406/209935044-16003fc6-6d4f-4798-9a07-8fd8505b0ea1.png)
With hover:
![image](https://user-images.githubusercontent.com/20357406/209935066-cfabb9ac-1694-41b9-bf94-6ac12f636456.png)

{i} when hovering over it, wont show extra information. You will see all items make room for a box of text.

**Comment by FrancescoBorzi** [comment]
caused by https://github.com/valor-software/ngx-bootstrap/issues/6490
