### ISSUE TITLE
ToolTip missing for some fields

### ISSUE THREAD

**Issue by Th3AnG3L** [azerothcore/Keira3#2076]
Hello,
Example what i mean inside Item Template when you edit fields some of them has tooltip and you understand for what is it, others are just empty fields and try to guest for what is used

example: trigger_1 what is it what it does etc..

Another question.
I'm trying to create an new item like hearthstone, that will  teleport Player to specific coordinates, how i can do that with this tool i cant find how to make it

**Comment by Helias** [comment]
I don't know if there are examples in the wiki, but probably the wiki should be more detailed about this

**Comment by Th3AnG3L** [comment]
nope, already checked. It's better to be implemented in software like the others ToolTips easy fast and understandable :)

**Comment by Helias** [comment]
if you mean the spell triggers checking the documentation you can easily get this list of values

![image](https://user-images.githubusercontent.com/519778/217096154-ac0db7ce-e7c6-4081-ab5a-42d4e4191433.png)

I am making a PR to improve the editor to show directly these values
