### ISSUE TITLE
[Bug Report] Looking up weapon item templates with models gradually makes Keira more resource-intensive

### ISSUE THREAD

**Issue by Gultask** [azerothcore/Keira3#2112]
![image](https://user-images.githubusercontent.com/100873791/213594400-f093d13f-268c-46a0-bf5e-ca1b67485bcb.png)

I was looking at NPC Equip items for a long time, after a while I noticed Keira was much slower and unresponsive. Looking at the task manager revealed this.

It seems like only weapons cause this, since they have displayed models.

Edit: This is with version 3.5.1

**Comment by Helias** [comment]
I recently updated it and now the model viewer is enabled also for gameobjects and NPCs, I do not know if this memory usage happens even now, but sure, we delegate to wowhead this 3D model and it will probably consume a lot of memory

**Comment by Gultask** [comment]
Ooooh that's why some of the models are more modern :D 
I was wondering why.

**Comment by Helias** [comment]
should be better in the next release, if not, it is something that we cannot improve except if we use a different implementation of 3D view model using the library linked here https://github.com/azerothcore/Keira3/issues/1787
