### ISSUE TITLE
[SAI Editor] Wrong Comment when using Waypoint Events with event_param1 set to 0

### ISSUE THREAD

**Issue by Gultask** [azerothcore/Keira3#2159]
When using Waypoint-type events and while using parameter 0 for PointId, the comment will say On Waypoint 0 Reached/Ended/etc. This is wrong as a point 0 cannot exist. The correct comment should be:

On Any Waypoint Reached/Ended/etc

![image](https://user-images.githubusercontent.com/100873791/219906265-df0f6dad-e205-4d49-8f7f-453af7316683.png)

**Comment by Helias** [comment]
improved here https://github.com/azerothcore/Keira3/pull/2160
