### ISSUE TITLE
[Question] creating inherited items

### ISSUE THREAD

**Issue by xBarselonx** [azerothcore/Keira3#2166]
Not long ago I decided to create inherited items besides those that are in the supplement 3.3.5a, namely the head, neck, back, hands, feet, etc.  As the basis took one of the inherited items (I do not remember exactly) by copying and changing the stat and purpose. As a result, I created 31 items in item_template table without world.
Is it possible to create these items by copying? I use AzerothCore-wotlk-with-NPCBots (https://github.com/trickerer) as server source files. The created items were primarily intended for NPC bot, not to bother with their equipment in the future. But I have a problem with the fact that after equipping them with these items, they get a large health index. For example, my character has about 600 units, and the bot has about 6000. Through the program Keira3, I did lowering the characteristics of created items, but nothing changed. Please help me with this issue. I can skype sql data created objects, may be I do something wrong. Doing it for the first time.

**Comment by Helias** [comment]
I did not understand which kind of items do you want to create on Keira3.

About the NPCs health I think you can play a bit with the HealthModifier fields present in item_template to change the NPC HP

**Comment by xBarselonx** [comment]
> I did not understand which kind of items do you want to create on Keira3.

Apparently my English leaves a lot to be desired))).
I meant items that are tied to an account. For example - https://wowgaming.altervista.org/aowow/?item=48685. Using Keira3 I wanted to create all necessary items (Binds to account), whose characteristics (health, armor, strength, etc.) increased with the level of the NPC bot.

**Comment by Helias** [comment]
I do not know how the NPCbot scripts work but if you can create those items manually without Keira3 you should be able to create them also with Keira3.
If you are asking how to create this kind of item based on the NPC level increase the properties I do not know :S, if they are entity of item_template I think so
