### ISSUE TITLE
[[Question]]3.5.2 creature->Spawn could not execute sql cause modelid dont exist

### ISSUE THREAD

**Issue by kingsring** [azerothcore/Keira3#2172]
When I try to execute a sql statement here, an error occurs, I checked the database, there is no item for modelid in the table. My az version is commit:b263f45189f6c3b1fff7d4638f963ba4bdd3196d

**Comment by kingsring** [comment]
Forgive my bad English, I think you can understand LOL

**Comment by Helias** [comment]
try to update your AC database structure with the latest version please

**Comment by Gultask** [comment]
And update your Keira too if you haven't already 😁 

While the modelid field is still there in the editor, don't fill it out and the output will be fine.
AC dropped the modelid field some time ago.
