### ISSUE TITLE
[Bug Report] SAI Editor sometimes fails to generate comments

### ISSUE THREAD

**Issue by Gultask** [azerothcore/Keira3#2174]
Open SmartAI tab
Search by entity -> Timed Actionlist -> 2034400
Generate Comments. All comments there are custom so the Generate Comments should update every row. But it does not.

Behaviour is version 3.5.1:

https://user-images.githubusercontent.com/100873791/221333640-b4cbe742-dbc3-46b9-b7aa-d19f8a6bd491.mp4

**Comment by Helias** [comment]
weird, I will investigate
I was thinking to put two buttons "Generate all comments", "Generate comment" so the user can choose to generate the comments for all or only for the selected row

**Comment by Gultask** [comment]
That's a good idea!
It'd also effectively close https://github.com/azerothcore/Keira3/issues/2107 as well
