### ISSUE TITLE
VisibilityDistanceType  tooltip is outdated.

### ISSUE THREAD

**Issue by avarishd** [azerothcore/Keira3#2180]
For creature_template_addon && creature_addon
https://www.azerothcore.org/wiki/creature_addon#visibilityDistanceType
https://github.com/azerothcore/azerothcore-wotlk/blob/8635ab01706a76f2476d7c918b6165b98ca960bf/src/server/game/Entities/Object/ObjectDefines.h#L60
```
Normal = 0, 100.0f // default visible distance, 100 yards on continents
Tiny = 1, 25.0f
Small = 2, 50.0f
Large = 3, 200.0f
Gigantic = 4, 400.0f
Infinite = 5, SIZE_OF_GRIDS // max distance for visible objects)
```

![9a8fb08647b661bd718fd3ea6b872bf3](https://user-images.githubusercontent.com/46330494/221920322-289e3697-9383-4476-adfc-b53cf0a59316.png)

**Comment by Helias** [comment]
fixed here https://github.com/azerothcore/Keira3/pull/2181
thanks
