### ISSUE TITLE
3.5.2 incompatible with Windows 7 64?

### ISSUE THREAD

**Issue by duncrafter** [azerothcore/Keira3#2212]
After downloading the new release, each time I try to start Keira,
I get an error message stating that "GetPackageFamilyName was not found in kernel32.dll".
As GetPackageFamilyName was added in the Windows 8 update (as far as I know), is Keira not compatible with Windows 7 anymore or could this be a bug or error on my part?

**Comment by Helias** [comment]
Personally I did not test Keira3 on Win7, I recommend you to upgrade

**Comment by duncrafter** [comment]
Thank you, I will be upgrading to Windows 10 soon
