### ISSUE TITLE
Keira3 feels very laggy and completely freezes in 3.5.2

### ISSUE THREAD

**Issue by Sulan2** [azerothcore/Keira3#2247]
Im having huge lags in creature template and SMART AI editor in 3.5.2, I feel like the creature template problem is the model viewer but the SMART AI editor doesnt have any viewer so it doesnt explain why that lags, did all my tooltip changes cause the program to lag more? 

In the Editor its mostly the 3 menu lists  in General, Event Action Target that doesnt load

Im still using 3.5.1 which doesnt have the creature model viewer and it doesnt lag anything, not even in SMART AI editor

**Comment by Helias** [comment]
we could add an option like "use 3D model viewer beta" to enable/disable this feature

**Comment by Sulan2** [comment]
> 

that would be great but I cant say if the viewer is the problem, I just assume it is. are u guys having lags/freezes aswell?

**Comment by Helias** [comment]
other users experienced lag for the 3d model viewer

**Comment by Samsequel** [comment]
@Helias 

We need an option, and possibly some garbage cleanup, it keeps the model in ram, and your ram just increases and increases the more you use it.

![image](https://github.com/azerothcore/Keira3/assets/20357406/5f660398-28a3-42ee-917f-c7d718df5e6e)
![image](https://github.com/azerothcore/Keira3/assets/20357406/3c18678f-5254-48d9-91f6-39829234e3a8)

**Comment by Helias** [comment]
I will do my best, but I am busy in the next two weeks :(

**Comment by Helias** [comment]
finally fixed https://github.com/azerothcore/Keira3/pull/2341 🎉
