### ISSUE TITLE
[Bug Report] SMART_EVENT_RANGE description is wrong

### ISSUE THREAD

**Issue by Nyeriah** [azerothcore/Keira3#2267]
![image](https://user-images.githubusercontent.com/47818697/230786018-744737a4-7f02-484f-98ee-b3a804c2ef8e.png)

It only ever checks for current victim, so no other target types allowed

![image](https://user-images.githubusercontent.com/47818697/230786044-b215985a-0ab8-4050-acca-a521137544e0.png)

**Comment by FrancescoBorzi** [comment]
@Nyeriah feel free to edit this string with a better description:

https://github.com/azerothcore/Keira3/blob/master/src/app/shared/modules/sai-editor/constants/sai-event.ts#L178

no need to checkout locally the app, you can just change the value of the string via GitHub and send a PR with it
