### ISSUE TITLE
bitmask -1 all values

### ISSUE THREAD

**Issue by Helias** [azerothcore/Keira3#2323]
it should enable all flags
![image](https://github.com/azerothcore/Keira3/assets/519778/10bc46a8-432d-4805-bf85-b1daf2cb58db)

**Comment by pangolp** [comment]
So `-1` and `2047` should return the same result? Because from what I see in the DB, the value is unsigned, I'm surprised that a negative value can be stored. Although it is true, I have seen it on several occasions.

`AllowableRaces` smallint(5) unsigned NOT NULL DEFAULT '0'
