### ISSUE TITLE
Keira3 made permanent changes to the database

### ISSUE THREAD

**Issue by clsto88** [azerothcore/Keira3#2333]
Hi, I'm new to modding . I downloaded Keira3 to mod some items stats, but when i tried to revert back to the previous stats and go back in the game it doesn't change! It stays like the first value modded with Keira3 . I tried to rebuild the database but it doesn't work, it's still the same. Does this have something to do with the privileges in SQL or  is Keira3 store info somewhere else?
Thanks for replies!

**Comment by Helias** [comment]
if on Keira3 reconnecting to the database you see the correct data of the items and in-game you see old data, you have to clean your client cache to see correctly the item data.

Let me know if cleaning your cache it works

**Comment by clsto88** [comment]
Thanks! It worked! Now i discovered another problem too! xD 
When i try adding block rating, critical rating, haste or any of those to an item it doesn't show in game. And some items can't even get basic stats like strength. Any ideas?

**Comment by Helias** [comment]
I think it's always an issue about cache or, there is a limit on the client side of some item attribute values, but I think that it is still an issue about the cache.

I am closing the issue, considering that it is at least partially solved and it is not an issue of Keira3.
