### ISSUE TITLE
SAI Editor: New event_param

### ISSUE THREAD

**Issue by Gultask** [azerothcore/Keira3#2394]
Needs to update the UI, ~~query generator~~ & allow support for tooltips and such

https://github.com/azerothcore/azerothcore-wotlk/pull/16944

**Comment by Gultask** [comment]
Not *exceptionally* high priority. It has a default so queries won't break, and only 2 events will use it so far.

**Comment by Gultask** [comment]
@Helias PR was just merged :), also the query generator already works, actually.

**Comment by Helias** [comment]
to add the new event_param6 I think we need a bit of rework, especially for the unit-tests
