### ISSUE TITLE
wowhead 403 forbidden

### ISSUE THREAD

**Issue by Helias** [azerothcore/Keira3#2493]
Wowhead does not allow to receive the texture png files anymore

**Comment by Helias** [comment]
https://github.com/Miorey/wow-model-viewer/issues/39

**Comment by FrancescoBorzi** [comment]
We are aware that this is affecting all Keira3 releases and @Helias is on it.

**Comment by Helias** [comment]
closed by https://github.com/azerothcore/Keira3/pull/2626
