### ISSUE TITLE
Quest Template RewardDisplaySpell & RewardSpell (i) is Gibberish

### ISSUE THREAD

**Issue by StraysFromPath** [azerothcore/Keira3#2601]
![image](https://github.com/azerothcore/Keira3/assets/119371540/92639968-ad6c-4542-ba37-47858f7e9098)

![image](https://github.com/azerothcore/Keira3/assets/119371540/bd6062cb-fb45-4612-b0e6-9a94bfab8d46)

I cannot parse what this means.

RewardSpellCast does not exist.

I am aiming to have a quest teach the player a Taunt spell upon quest completion (like how druid quests teach druid forms).

Taunt Spell = 70428

Option A:
RewardDisplaySpell 0
Reward Spell 0
No effect.

Option B:
RewardDisplaySpell 70428
Reward Spell 0
No effect.

Option C:
RewardDisplaySpell 0
Reward Spell 70428
The NPC casts taunt on the player(???)

Option D:
RewardDisplaySpell 70428
Reward Spell 70428
No effect.

**Comment by Helias** [comment]
not sure how you could make this if changing the spell_dbc table server-side does not help
I am not sure that you really need to change the DBCs, but it might be necessary

**Comment by Helias** [comment]
btw, I don't think that this is an issue of Keira3, is more something related to the game or core system so I would close this issue if you agree

**Comment by StraysFromPath** [comment]
> btw, I don't think that this is an issue of Keira3, is more something related to the game or core system so I would close this issue if you agree

For Keira I'd change the (i) to something descriptively accurate like

"This is the spell that will be cast by the NPC onto the player when the quest is completed."

I still don't know what it means by RewardSpellCast = 0 because RewardSpellCast doesn't exist(?).
