### ISSUE TITLE
需要一个完整的汉化版本

### ISSUE THREAD

**Issue by 1825679767** [azerothcore/Keira3#2605]
虽然有汉化，但是仅限于标题，各类小选项还是英文，使用起来极其不方便，期待一个完整的汉化

**Comment by Helias** [comment]
Hi, you can contribute to improve the translations editing this file completing the missing parts
https://github.com/azerothcore/Keira3/blob/master/src/assets/i18n/zh.json

**Comment by 1825679767** [comment]
> 您好，您可以通过编辑此文件来改进翻译，完成缺失的部分 https://github.com/azerothcore/Keira3/blob/master/src/assets/i18n/zh.json
I also want to help with the translation, but I don’t understand code, I have the will but not the skill.

**Comment by Helias** [comment]
ok, if you can't translate the english strings on the "right" part we have to find someone that could do it from english with chinese.
Keep in mind that the strings to translate are for example:
```
 "CONDITION_TO": "Target to which relation is checked. One of the ConditionTargets available in current SourceType",
 ```
 
 we need to change the content on the right, so only this:
`Target to which relation is checked. One of the ConditionTargets available in current SourceType`
into the chinese language, for example
