### ISSUE TITLE
Wrong database link in creature_template_movement editor

### ISSUE THREAD

**Issue by ludwici** [azerothcore/Keira3#2646]
While editing the movement of creatures, I noticed that the "creature_template_movement" button opens the page https://www.azerothcore.org/wiki/creature_template_resistance

But it should open the page https://www.azerothcore.org/wiki/creature_template_movement
![image](https://github.com/azerothcore/Keira3/assets/12829363/7999ba71-55cb-4f90-981d-ac6fe8bd7c30)

**Comment by Helias** [comment]
true, fixed here https://github.com/azerothcore/Keira3/pull/2647
it will be added in the next release
