### ISSUE TITLE
[Feature Request] Automatically Calculate [count] when editing items.

### ISSUE THREAD

**Issue by StraysFromPath** [azerothcore/Keira3#2667]
There's a very unusual minigame when making items.

Each time you add an attribute (e.g agility) you must ALSO increase "count" by 1.

I think this could be automated by checking how many attribute fields have values and setting count to that.

This might seem like work at first, but this saves 30 seconds to 1 minute for every item made by every person.

If 500 people make 500 items a year, that's 4000 hours of human time saved by automatically calculating count.

It also makes editing easier/more accessible for new people as the clandestine test of "do you already know how count works - it's not explained anywhere but do you know?" is removed for new users.

**Comment by MKokeshi** [comment]
You're absolutely right, automating the "count" mechanic seems like a great way to improve efficiency and user experience! Here are some thoughts on your approach:

**Pros:**

- Time-saving: As you mentioned, automating the count could save a significant amount of time for users, especially with high production volume.

- Reduced errors: Manual counting is prone to errors, so automation can improve accuracy and data consistency.

- Improved accessibility: Removing the hidden "count" mechanic makes the process more transparent and easier for new users to understand and follow.

**Considerations:**

- Implementation complexity: The complexity of implementing the automation will depend on the specific platform or system used for item creation.

- Edge cases: It's important to consider how the automation will handle edge cases, such as:
        - Attributes with optional values (should they count even if empty?)
        - Dynamically added attributes
        - Different types of attributes (e.g., text vs. numerical)

- User perception: While the automation aims to improve user experience, it's essential to ensure it doesn't feel intrusive or remove user agency. Consider providing transparency about the automation and the option to override the count if needed.

Overall, automating the count seems like a positive step with several benefits. Carefully considering the implementation details and potential edge cases will ensure a smooth and successful integration.

**Comment by StraysFromPath** [comment]
What in the chatGPT nonsense is that.
