### ISSUE TITLE
[Bug] RewardFactions is completely wrong.

### ISSUE THREAD

**Issue by StraysFromPath** [azerothcore/Keira3#2678]
RewardFactions "value1" is a dbc lookup - not flat 7. 

Faction 47 is Ironforge, not venture company.

So the rewardfactions info is displaying wrong info for both amount and faction for all quests.

![image](https://github.com/azerothcore/Keira3/assets/119371540/345df10d-186b-40f5-bf16-767b5950cc61)

![image](https://github.com/azerothcore/Keira3/assets/119371540/374c11af-2e95-49f9-b70c-ad7e8f7f662c)

**Comment by Helias** [comment]
fixed, the fix will be included the next release
