### ISSUE TITLE
RewardFactionValue quest preview

### ISSUE THREAD

**Issue by Helias** [azerothcore/Keira3#2681]
fix reward faction value based on reputation_reward_rate table and dbc_questfactionreward.

we have to handle the following cases:
- Rew.FactionOverride* is present
- Daily/Weekly/Repeatable quests

source: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Player/Player.cpp#L5999

**Comment by FrancescoBorzi** [comment]
@Helias please don't forget the labels
