### ISSUE TITLE
TrinityCore support?

### ISSUE THREAD

**Issue by Aztec2012** [azerothcore/Keira3#2683]
TrinityCore support?

**Comment by Helias** [comment]
Would be a great thing but it's hard to keep the maintenance only for one core, keeping the support also for TC 335a would be really harder.
We are only two developers here with low time who are trying to do their best, we already share our project open-source so also other community can use this project and share fixes with us.

**Comment by FrancescoBorzi** [comment]
@Aztec2012 please read: https://github.com/azerothcore/azerothcore-wotlk/discussions/3920
