### ISSUE TITLE
Gameobject_template_addon Flags WRONG MASK description

### ISSUE THREAD

**Issue by chaosua** [azerothcore/Keira3#2718]
sometnig strange found
Keira proposes  Flags in Gameobject_template_addon from 1 to 256
But in core SharedDefines.h we have
enum GameObjectFlags : uint32
{
 **1**       GO_FLAG_IN_USE          = 0x00000001,                   // disables interaction while animated
**2**       GO_FLAG_LOCKED          = 0x00000002,                   // require key, spell, event, etc to be opened. Makes "Locked" appear in tooltip 
**4**       GO_FLAG_INTERACT_COND   = 0x00000004,                   // cannot interact (condition to interact)
**8**        GO_FLAG_TRANSPORT       = 0x00000008,                   // any kind of transport? Object can transport (elevator, boat, car)
**16**       GO_FLAG_NOT_SELECTABLE  = 0x00000010,                   // not selectable even in GM mode
**32**        GO_FLAG_NODESPAWN       = 0x00000020,                   // never despawn, typically for doors, they just change state
**64**        GO_FLAG_TRIGGERED       = 0x00000040,                   // typically, summoned objects. Triggered by spell or other events
_128_       (Here is absent FLAG   XXXXXXX = 0x000000**80**, **Trinitycore** says it GO_FLAG_FREEZE_ANIMATION
_256_        (Here is absent FLAG    XXXXXXY = 0x00000**100**,
**512**       GO_FLAG_DAMAGED         = 0x00000200,
**1024**       GO_FLAG_DESTROYED       = 0x00000400,
};
And AC wiki https://www.azerothcore.org/wiki/gameobject_template_addon#gameobject_template_addon-flags says thet last two mast be 512 and 1024
![keira1](https://github.com/azerothcore/Keira3/assets/544218/075efd36-3770-4ac2-8a96-d9a5cfda941c)

so the actual flags will be 1-64, (absent 128,  absent 256), 512 GO_FLAG_DAMAGED ,1024 GO_FLAG_DESTROYED       
Or I'm wrong?

**Comment by Helias** [comment]
You're right!

Thanks for this report, I made the fix, it will be in the next release

documentation updated in https://github.com/azerothcore/wiki/pull/945
the issue has been fixed here https://github.com/azerothcore/Keira3/pull/2719
