### ISSUE TITLE
Item Editing StatType2 is wrong for mana

### ISSUE THREAD

**Issue by StraysFromPath** [azerothcore/Keira3#2758]
It lists value 0 as mana, 1 as health, and 2 does not exist.

In reality value 0 is blank, 1 is health, I think 2 might be mana?

**Comment by Helias** [comment]
I think you're right, the stat type 0 should be "blank/null" and mana should be 2, but I can't find any item in item_template with stat_type* = 2, so it's probably unused.

By the way, I fixed this on https://github.com/azerothcore/Keira3/pull/2761

And I reported it in AoWoW https://github.com/Sarjuuk/aowow/issues/389, hope they can give us a second opinion.
