### ISSUE TITLE
[Feature Request] Add Sessions

### ISSUE THREAD

**Issue by Instantium** [azerothcore/Keira3#2918]
It's often hard to keep track of all the tables that where changed when an item, quest or anything is added. 

It would be nice to be able to create sessions for larger edits. 
I am thinking of something like this:
- Create a new Session
- Do all the changes
- The Session keeps track of all the changes and generates one single diff-sql

**Comment by Helias** [comment]
similar to https://github.com/azerothcore/Keira3/issues/1086 and point 2 of https://github.com/azerothcore/Keira3/issues/401
I am closing this as duplicate
