### ISSUE TITLE
[Feature Request] Display ID next to SourceTypeOrReferenceId in Conditions

### ISSUE THREAD

**Issue by sogladev** [azerothcore/Keira3#2988]
Condition tab doesn't show ID next to SourceTypeOrReferenceId. Currently have to navigate to wiki page (https://www.azerothcore.org/wiki/conditions) to link name to the id

Current: `SourceTypeOrReferenceId`

Request: `SourceTypeOrReferenceId - ID`

No numbers in condition tab
![condition_numbers](https://github.com/azerothcore/Keira3/assets/46423958/d25a411c-c585-486e-98c1-81bb5251cbf8)

IDs can be found on wiki
![numbers](https://github.com/azerothcore/Keira3/assets/46423958/2bf2d774-b907-4755-ae47-cdc9e06ed080)

Request to show IDs similar to how smartAI displays the ID and text

smart AI has numbers 
![numbers_smartai](https://github.com/azerothcore/Keira3/assets/46423958/9fbfb6dc-a536-4274-9611-e940da68b684)

**Comment by FrancescoBorzi** [comment]
@sogladev thanks for your suggestion, see https://github.com/azerothcore/Keira3/pull/2990

Minor note: I made it "VALUE - TEXT" instead of "TEXT - VALUE" to be consistent with other existing places like the SmartAI you mentioned.
