### ISSUE TITLE
Keira3 is now bricked for NPCs due to ModelID changes.

### ISSUE THREAD

**Issue by StraysFromPath** [azerothcore/Keira3#3027]
Some Acore changes are unwise. Renaming/deleting fields like ModelID, QuestReward, GetLevel, etc serve only to brick old code and break tools like this for no tangible benefit whatsoever.

![image](https://github.com/user-attachments/assets/2d99fc8f-269a-404c-ae4f-4aa434cc007e)

**Comment by FrancescoBorzi** [comment]
@StraysFromPath @samaelfox we will fix this as soon as we have the chance
