### ISSUE TITLE
Keira display preview for stat_type (42) and (41) are flipped

### ISSUE THREAD

**Issue by amed80** [azerothcore/Keira3#3040]
The side preview shows healing when you choose spell damage and spell damage when you choose healing
In game its shown correctly

![image](https://github.com/user-attachments/assets/5ed65ecd-7fe8-43b6-84bd-6391540c5e3e)
![Keira3_13%40%14=30-08-2024](https://github.com/user-attachments/assets/f1f871f1-8173-44d3-9d03-331a5f977065)

**Comment by Helias** [comment]
I fixed the issue in this PR https://github.com/azerothcore/Keira3/pull/3042
it will be available in the next release.

This problem was present also on AoWoW (wowgaming) and it has been fixed here https://github.com/azerothcore/aowow/pull/52

thanks for the report!
