### ISSUE TITLE
Creature -> Text: Selection does not update edit fields 

### ISSUE THREAD

**Issue by sudlud** [azerothcore/Keira3#3053]
tested on Keira 3.7.1

Open Keira3
-> Creature
-> e.g. ID 29
-> open Creature -> Text

click on first text line
-> UI edit fields update for this line

now click on any other text line
-> UI edit fields do not update for the selected line
-> UI edit fields will always show the entries for the first selected line

**Comment by TheSCREWEDSoftware** [comment]
Can confirm the issue above to correct that the value display above is always the first value in the list and not the first one selected.

**Comment by Helias** [comment]
that is just to define the type, which is an int so `0` and not a string like `"0"`, moreover running
```sql
DESCRIBE acore_world.creature_text;
```
I see that the default value is 0 in the SQL table, so it should be correct.

Thanks for asking ;-)

By the way, I can also confirm the bug, hope to find a solution

**Comment by TheSCREWEDSoftware** [comment]
Could you tell me within the code of keira where the function that searches for that ID is?

**Comment by Helias** [comment]
it's in multi-row-editor.service.ts, it takes in the constructor the field value from creature-text.service.ts

**Comment by Helias** [comment]
I strongly think that I missed to add some logic here https://github.com/azerothcore/Keira3/pull/3038
I will check it in the next days

**Comment by TheSCREWEDSoftware** [comment]
In Gossip => Select Gossip Menu => TexID 1651

I was trying to see where this logic in the constructor is, because here it works as intended (just has 1 value)

**Comment by Helias** [comment]
checking it better, you're right @TheSCREWEDSoftware, but we have to implement on keira3 a way to manage a third Primary Key in a table (and maybe even more if necessary)
Right now with https://github.com/azerothcore/Keira3/pull/3102 the issue reported is fixed but we need to manage when a user use same GroupID in multiple rows with different IDs
