### ISSUE TITLE
creature_template's content not propely updating after running SQL via the SQL Editor

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/Keira3#3059]
1 - Create (new) creature_template entry

2 - Go to creature_template

Lets use `90000001`

<details>
<summary>Entry Created</summary>

![image](https://github.com/user-attachments/assets/fb7eb35c-220e-4c2e-9baf-4999fa056bf5)

</details>

3 - (you can skip this part if you're using my example entries and SQL) Go back to select creature of your choice, we will use 
Kobold Miner (Entry: 40)

4 - Go that creature's template and click on full-query on top and copy that SQL and edit it

From:
```SQL
DELETE FROM `creature_template` WHERE (`entry` = 40);
INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `speed_swim`, `speed_flight`, `detection_range`, `scale`, `rank`, `dmgschool`, `DamageModifier`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `spell_school_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES
(40, 0, 0, 0, 0, 0, 'Kobold Miner', NULL, NULL, 0, 6, 7, 0, 26, 0, 1, 0.85714, 1, 1, 18, 1, 0, 0, 1, 2000, 2000, 1, 1, 1, 0, 2048, 0, 0, 0, 0, 0, 0, 7, 0, 40, 40, 0, 0, 0, 1, 12, 'SmartAI', 1, 1, 1, 1, 1, 1, 0, 100, 1, 0, 0, 0, '', 12340);
```
to 
```SQL
INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `speed_swim`, `speed_flight`, `detection_range`, `scale`, `rank`, `dmgschool`, `DamageModifier`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `spell_school_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES
(90000001, 0, 0, 0, 0, 0, 'Kobold Miner', NULL, NULL, 0, 6, 7, 0, 26, 0, 1, 0.85714, 1, 1, 18, 1, 0, 0, 1, 2000, 2000, 1, 1, 1, 0, 2048, 0, 0, 0, 0, 0, 0, 7, 0, 40, 40, 0, 0, 0, 1, 12, 'SmartAI', 1, 1, 1, 1, 1, 1, 0, 100, 1, 0, 0, 0, '', 12340);
```
5 - Go to SQL Editor and run the SQL you've changed that mathces your created entry in our case `90000001`
You should get a message saying 1 row was affected

6 - Go back to select creature and search for your entry id, our case: `90000001`

<details>
<summary>Select Creatured Updated</summary>

![image](https://github.com/user-attachments/assets/dca08f6e-95d3-4e06-b667-d05f6043285f)

</details>

<details>
<summary>Creature Template doesnt update</summary>

![image](https://github.com/user-attachments/assets/959538bf-7782-44ad-9861-1c8d10430d84)

</details>

<details>
<summary> Creature Template only updates after restart</summary>

![image](https://github.com/user-attachments/assets/c6cc8461-de9d-4320-95b2-9cdb9729c1f1)

</details>

I was able to 2 / 3 times have this issue. Where 1 of the times I had 2 changes in the SQL (dropped 40 by mistake) and that cause the same issue, but the other was only 1 changed and had the same issue.

**Comment by Helias** [comment]
fixed here https://github.com/azerothcore/Keira3/pull/3101
