### ISSUE TITLE
[Enhancement] - creature_equip_template Information for IteamID1 to 3

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/Keira3#3122]
In `creature_equip_template` add Information to ItemID1 to ID3

Quoting from Wiki

> ItemID1
> This is the item number of the equipment used in the right hand from [Item.dbc](https://www.azerothcore.org/wiki/Item).
> 
> ItemID2
> This is the item number of the equipment used in the left hand from [Item.dbc](https://www.azerothcore.org/wiki/Item).
> 
> ItemID3
> This is the item number of the equipment used in the ranged slot from [Item.dbc](https://www.azerothcore.org/wiki/Item).

 ![image](https://github.com/user-attachments/assets/7fe76397-d7c1-45d6-b7bc-27b4e4b20d1b)

**Comment by Helias** [comment]
Thanks for all these issues, by the way, adding a tooltip should not be hard to do, you can also try to implement it, otherwise I hope to find the time in the weekend

**Comment by TheSCREWEDSoftware** [comment]
Resolved in: https://github.com/azerothcore/Keira3/pull/3124
