### ISSUE TITLE
[Suggestion] - Add Keira3 Internals (content) or link to Keira3 Page

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/Keira3#3136]
I think that the contents or link (that's on the bottom of the readme.md in Github) should be part of the main Keira Page. Not even if it's at the bottom or part of the navbar. Refered as Documentation or Internal

**Comment by rafaelgpaves** [comment]
Hi! I Wanted to work on this, but isn't it already implemented? The footer has a "Dev's docs" link that goes to the [internals page](https://www.azerothcore.org/wiki/keira3-internals)

**Comment by TheSCREWEDSoftware** [comment]
You're correct indeed, its seem I've missed at the footer. Tho i would still suggest it either to be added to the navbar or probably changed to match the ac's page "Interals" or be called "Documentation"

**Comment by rafaelgpaves** [comment]
Ok! @Helias can I work on this?

**Comment by Helias** [comment]
Hi, yes you can ;-)

**Comment by TheSCREWEDSoftware** [comment]
Valeu my friend. Thanks for the nav bar addiition, closing Issue.
