### ISSUE TITLE
Creature Editor

### ISSUE THREAD

**Issue by benvalmont** [azerothcore/Keira3#3141]
Seach in Creature Editor still comes up empty

**Comment by Helias** [comment]
could you be more specific? the issue is not clear to me

**Comment by benvalmont** [comment]
What i meant is when I go in Select Creature, and search for creature name, entry comes up empty
![Uploading Screenshot_5.png…]()

**Comment by benvalmont** [comment]
This is the screenie

[https://ibb.co/0rH2B6n](url)

**Comment by benvalmont** [comment]
Oh, okay, thats the issue, thanks
