### ISSUE TITLE
Bitmask for socketColor_# not displaying correctly

### ISSUE THREAD

**Issue by blinkysc** [azerothcore/Keira3#3142]
When using the ... for bitmask values for gems the bitmask applying incorrect values.

To Reproduce:

item 50735
Color_1 = 2 Red
Color_2 = 8 Blue
Color_3 = 4 Yellow
Use ... helper and notice it thinks 2 is bit 1 (Meta) and setting as red will apply 4 as value

![image](https://github.com/user-attachments/assets/a264c21b-9586-4d04-911c-c83c30ac429e)

**Comment by TheSCREWEDSoftware** [comment]
@Helias and @FrancescoBorzi provide me with some insight, i was looking into this issue but i dont see anywhere in the item_template in AC or even in TC where it mentions that ScoketColours should be a bitmask. They are just a value.

You either choose it's a Meta, red, yellow or blue gem. isn't npcflags. right?

AC
![image](https://github.com/user-attachments/assets/92e2d669-6deb-4316-879e-54088bbbecae)

TC
![image](https://github.com/user-attachments/assets/9c9ce5c4-7089-48cc-9c10-45357f6b8c78)

If i introduce the value manually (not the bitmask)

I can change to the proper gem

**Comment by Helias** [comment]
Yes we could switch this into a `keira-generic-option-selector`

**Comment by FrancescoBorzi** [comment]
>  i was looking into this issue but i dont see anywhere in the item_template in AC or even in TC where it mentions that ScoketColours should be a bitmask

Eeemh sorry to be the party pooper but it actually really looks like it is a bitmask. Because 1, 2, 4, 8 are indeed powers of 2

And there are indeed composite values (even rare):

![image](https://github.com/user-attachments/assets/bc02ebaa-0f58-46e3-8d53-ab48070938de)

14 for example is 8+4+2 so it must be bitmask. The problem is probably that the values are a bit off. I'm going to look into it.

**Comment by FrancescoBorzi** [comment]
I'm thinking that the fix should rather be:

![image](https://github.com/user-attachments/assets/69f5df72-ceea-4677-895d-74943dbf3403)

As the `bit` in flags represent the POWER of 2 (not the final value).

In this example:

- bit `0` means `2^0` = `1`
- bit `1` means `2^1` = `2`
- bit `2` means `2^2` = `4`
- bit `3` means `2^3` = `8`

**Comment by FrancescoBorzi** [comment]
> Those are the only 4 items that follow that rule of bitmask and these items are not obtainable, probably they were test items.

I agree, but I think it is a better idea to keep supporting flags so people can create more customised sockets that support multiple colours :)

**Comment by TheSCREWEDSoftware** [comment]
> > Those are the only 4 items that follow that rule of bitmask and these items are not obtainable, probably they were test items.
> 
> I agree, but I think it is a better idea to keep supporting flags so people can create more customised sockets that support multiple colours :)

What do you meany by multiple colours, now im confused ^^"
