### ISSUE TITLE
Keira upon `Execute & Copy` doesn't care if the execution is correct or not refering to the clipboard

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/Keira3#3175]
I don't know what to qualify this as a bug or a enchancement.

I used this on `creature_template` and `SAI` so either of them will work for this example.

- Have this number in your clipboard `11625`
- Go to Creature Template
- Search for ID `11625` (reflects to be: `Cork Gizelton`, click him
- Any value that's required (can't be null), let's use `minlevel` either remove it (and keep it blank) or use a negative number like `-1`
- Press `Execute & Copy`
- You will get the SQL error and now your clipboard still got overwrriten by the command.
You went from `11625` to (example) below: 
``` sql
UPDATE `creature_template` SET `minlevel` = -1 WHERE (`entry` = 11625); 
```

I'm not sure how it works in TypeScript.

Have a variable with the query (even if wrong).

Check if the query is correct, if yes, execute it, and grab the query and overwrite the user's clipboard.

If the query is not correct or there's an issue executing (for some reason), don't touch the user's clipboard

(if you tell me where this comparasition happens i can probably fix it and submit a PR)

**Comment by Helias** [comment]
right now we don't do a comparison, we execute the SQL query and at the same time we make the copy, we should make a proper function to do this check I think

**Comment by FrancescoBorzi** [comment]
> Check if the query is correct

the problem is that TypeScript has no idea if the query executes successfully or not until it is actually executed, so unfortunately this cannot be implemented.
