### ISSUE TITLE
[Suggestion] Add comment in creature table.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/Keira3#3182]
I propose adding the Comment feature in the creature table (Spawn Section).

**Comment by Exitare** [comment]
Hi @Rorschach91 ,
is this idea related to an sql comment like  
 -- Single line comments 
 so that the sql is clearer?

**Comment by Rorschach91** [comment]
> Hi @Rorschach91 , is this idea related to an sql comment like -- Single line comments so that the sql is clearer?
> 
> Is there a reference I can review ?

I mean that the feature comment should be added in the Creature Spawn Section for every Creature Guid.
Currently Keira3 doesn't have this feature, so the comments can only be showed using other tools (MySql Workbench for example).

Examples:

(Creature Table on MySql Workbench)
![comment](https://github.com/user-attachments/assets/6f316438-ad75-4fb9-9bd1-743ded7b567e)

How it should be in Keira3:
![creature table](https://github.com/user-attachments/assets/239a1a3e-e0ee-4d8b-a01e-7ecd6790eabf)

**Comment by Exitare** [comment]
@Rorschach91  PR is up. Feel free to test it, if possible!
