### ISSUE TITLE
i18n files are not in sync.

### ISSUE THREAD

**Issue by Exitare** [azerothcore/Keira3#3211]
While adding new translations I realized that some files have Key Value Pairs that are unique to the file and are not used in other files. 

E.g.

es.json

```json
 "PAGE_TEXT": "Page Text",
 "PAGE_TEXTS": {
        "ID": "The ID of the text in the page. This number is unique to every text ID.",
        "NEXT_PAGE_ID": "The ID of the next page's text ID.",
        "TEXT": "The actual text. The message in this field will be shown as the text on a page."
}
```

While almost all other files use:
```json
"SELECT_PAGE_TEXT": "Select Page Text",
"PAGE_TEXT": "Page Text"
```

I dont know what the best thing to do here is, or if it is even worth the time to correct that, as probably the majority will use Keira in English anyway?

**Comment by Helias** [comment]
Fair point!
Ideally, we should have all the keys in all translations *.json files. We should implement a GitHub action that makes this check and adds automatically the missing keys, instead of correcting them manually

**Comment by Exitare** [comment]
sorry for the delay. 
I think in this case the keys for the es version are not used. ( I have to check though)
but if thats correct, we would have to remove them instead of adding them to the other files.

**Comment by Helias** [comment]
> sorry for the delay. I think in this case the keys for the es version are not used. ( I have to check though) but if thats correct, we would have to remove them instead of adding them to the other files.

we could remove all the unused keys, for the rest we should keep/add them
