### ISSUE TITLE
[Request][Feauture] New options: auto-recconect or keep-alive

### ISSUE THREAD

**Issue by wlasser** [azerothcore/Keira3#343]
Hello there.
Keira is good, but with some reasons with working on remote machine - app is disconnected affter sometime (this is normal, i think), but force-reload and reload options do same thing - just kick you on connection settings window. 
I think improvments with timed-out connection can reduce madness with it.
For example HeidiSQL don't have this issue.
When Keira is lost connection - the status changed to red.

**Comment by Helias** [comment]
Thanks you for your feedback, but how do you work on a remote machine with Keira3?
Do you use any tunneling?

**Comment by wlasser** [comment]
No, direct connection.
