### ISSUE TITLE
SAI: Disable event type if using timed action lists

### ISSUE THREAD

**Issue by Stoabrogga** [azerothcore/Keira3#353]
If using timed action lists (source_type 9 "SMART_SCRIPT_TYPE_TIMED_ACTIONLIST") the event type should be set to 0 and disabled. The action lists only use event param1 and param2 to specify a minimum / maximum wait time, they (obviously) don't use events, as those are just sequentially executed actions.

**Comment by FrancescoBorzi** [comment]
it's now in `master` branch and will be part of next release, thanks @Stoabrogga for the suggestion!
