### ISSUE TITLE
[FEATURE REQUEST] SAI Actionlist handling

### ISSUE THREAD

**Issue by Jinnaix** [azerothcore/Keira3#379]
As mentioned in Discord:

If you pick a creature for SAI editing, it would be nice to see all aviable actionlists for that creature.
In addition, jumping back and forth with a simple click to take them into editing would be nice too.

Example - Trinitycores Version of AoWoW shows all aviable actionlists for creatures :
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=15402#sai-main

**Comment by FrancescoBorzi** [comment]
Not sure about this part, as it can be tricky and quite time-consuming to implement:

> In addition, jumping back and forth with a simple click to take them into editing would be nice too.

however displaying the list of actionlists for creatures should be doable.
