### ISSUE TITLE
Suggestions to improve: preview of items, quests, etc...

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/Keira3#405]
https://www.youtube.com/watch?v=R9oQs5KlEBo&feature=emb_logo
It would be good if we could:

- [x] visualize the items in 3D;
- [x] have better ergonomics with maybe icons that at a glance show us the option;
- [x] visualize, as in the video, the item we are creating;
- [x] also visualize the quest we are creating;
- [ ] can be created an algorithm that automatically calculates the level of the item based on the statistics.

**Comment by Helias** [comment]
About item level, we can get inspired by https://www.reddit.com/r/wow/comments/99bxio/data_on_item_level_scaling/

**Comment by BarbzYHOOL** [comment]
not sure it's related and also it's for last WOW version

btw I bet the formula would be the easiest thing to find for this lol and there is a lot of data on wowpedia to get from

just take 3 items, compare the stats and the ilvl, find a formula that matches the 3 of them, done

**Comment by Helias** [comment]
@BarbzYHOOL if you find it could be very nice xD
But we need to be sure that it works for all items

**Comment by BarbzYHOOL** [comment]
no time atm but if needed i could try (looks fun)

**Comment by FrancescoBorzi** [comment]
As this suggestion actually contains several things, I've started to break it down into multiple child-issues so we can address them one by one:

- https://github.com/azerothcore/Keira3/issues/456
- https://github.com/azerothcore/Keira3/issues/457
- https://github.com/azerothcore/Keira3/issues/459
- https://github.com/azerothcore/Keira3/issues/458

**Comment by Helias** [comment]
The issues listed by @FrancescoBorzi are closed now and available in the [last release](https://github.com/azerothcore/Keira3/releases/tag/v3.0.0-rc.0).
We implemented the **Item preview** and the **Quest preview**.

The missing features are:
- [ ] visualize the items in 3D;
- [ ] can be created as an algorithm that automatically calculates the level of the item based on the statistics.

I think that we should open a separate issue for each one.

About the item 3D visualization, I really considered it, but it's not so easy to implement and you can only see the 3D model but can't properly edit/add so it's not so useful I think.
Anyway, I hope to add it in the future.

About the item level, open a separate issue and suggest how to calculate it.

**Comment by Helias** [comment]
Thanks to https://github.com/azerothcore/Keira3/pull/1780, it is missing only the last feature requested now

**Comment by Helias** [comment]
i did some research, I don't think it's feasible to make an automated calculation of the base item level property, if anyone has a proper formula that we could implement I can re-open this issue and implement it.
