### ISSUE TITLE
File contains a virus or potentially unwanted software.

### ISSUE THREAD

**Issue by rondellivey03** [azerothcore/Keira3#447]
[Screenshot Here](https://i.postimg.cc/1XCsQLDr/A1.png)

I attempted to download Keira3 from the Release tab. [This here to be exact.](https://github.com/azerothcore/Keira3/releases/tag/v3.0.0-beta.2) and every-time I try to unzip it to my desktop, it brings up the "File contains a virus or potentially unwanted software." error then removes both Keira3 & the zip folder.

It says the file is detected as a Trojan..

**Comment by FrancescoBorzi** [comment]
@rondellivey03 thanks for your report. Does it happen with the previous releases ? For example, with beta1 ? or is this happening only with beta 2 ?

**Comment by rondellivey03** [comment]
> 
> 
> @rondellivey03 thanks for your report. Does it happen with the previous releases ? For example, with beta1 ? or is this happening only with beta 2 ?

I just tested beta 1, and it doesn't do that, I've also tried Beta 0 & Alpha 3.
Just this latest release its doing that.

**Comment by Helias** [comment]
Try this version 
https://mega.nz/#!91YnnAKR!1R_jcoPJCrZlNPxYSB42L4-FX-hhyN-YijcUuiVhke8

**Comment by rondellivey03** [comment]
That worked without a problem.

**Comment by Helias** [comment]
Ok, so I will upload this version on github and close this issue ;-)
Thanks a lot for testing!

**Comment by FrancescoBorzi** [comment]
thanks @rondellivey03 for reporting this issue and @Helias for the fix

Windows... what a strange operating system!
