### ISSUE TITLE
[EPIC] Quest preview

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/Keira3#457]

**Comment by Helias** [comment]
- [ ] Loremaster
- [x] Races 
- [x] Side / Faction
- [ ] Start / End
- [ ] Sharable
- [ ] Difficulty
- [ ] Quest Chain
---- 
- [ ] Relevant Locations
- [ ] Description
- [ ] Progress
- [ ] Completion
- [ ] Rewards
- [ ] Gains
