### ISSUE TITLE
Update to latest ngx-highlightjs

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/Keira3#485]

**Comment by FrancescoBorzi** [comment]
currently blocked by: https://github.com/MurhafSousli/ngx-highlightjs/issues/119

**Comment by FrancescoBorzi** [comment]
Update: still blocked by https://github.com/MurhafSousli/ngx-highlightjs/issues/97#issuecomment-727271753

**Comment by Helias** [comment]
closes by https://github.com/azerothcore/Keira3/pull/1792
