### ISSUE TITLE
Error Unknown^ please help

### ISSUE THREAD

**Issue by crotin1111** [azerothcore/Keira3#50]
it does this on any folder.

Also i have no idea how to install npm. its unclear. please upload a video explained or just a video..

C:\WINDOWS\system32>npm run ng:serve:web
npm ERR! path C:\WINDOWS\system32\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sheldon Gelinas\AppData\Roaming\npm-cache_logs\2019-08-15T02_10_37_902Z-debug.log

**Comment by crotin1111** [comment]
C:\ACORE BUILD\Keira3>npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\ACORE BUILD\Keira3\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\ACORE BUILD\Keira3\package.json'
npm WARN Keira3 No description
npm WARN Keira3 No repository field.
npm WARN Keira3 No README data
npm WARN Keira3 No license field.

up to date in 1.126s
found 0 vulnerabilities

**Comment by crotin1111** [comment]
now i realized i had to download the first zip.
yet i have no idea how to run it.

**Comment by crotin1111** [comment]
C:\ACORE BUILD\Keira3\Keira3-master>npm run build

> Keira3@3.0.0-alpha.1 build C:\ACORE BUILD\Keira3\Keira3-master
> npm run postinstall:electron && npm run electron:serve-tsc && ng build


> Keira3@3.0.0-alpha.1 postinstall:electron C:\ACORE BUILD\Keira3\Keira3-master
> node postinstall


> Keira3@3.0.0-alpha.1 electron:serve-tsc C:\ACORE BUILD\Keira3\Keira3-master
> tsc -p tsconfig-serve.json


chunk {main} main.js, main.js.map (main) 1.02 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 287 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 392 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.09 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 47.3 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.31 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 5.97 MB [initial] [rendered]
Date: 2019-08-15T03:06:27.664Z - Hash: d6ab0232bfa85df2ee7e - Time: 127534ms

**Comment by crotin1111** [comment]
yet localhost 4200 wont work^

**Comment by crotin1111** [comment]
well localhost works. idk what i did wrong but the connect button is broke^

**Comment by crotin1111** [comment]
This command does not build an exe app

npm run electron:windows

**Comment by crotin1111** [comment]
Success! actuallly it did have exe just didnt look the rite place! amen have a good day

**Comment by milestorme** [comment]
Good job bro , if the guide on the readme isn’t complete feel free to do a pull request with updated instructions if you learned anything that can help others .

**Comment by FrancescoBorzi** [comment]
@crotin1111 were you trying to run Keira3 in development mode or you just want to run it normally?

**Comment by crotin1111** [comment]
I was just trying to run it normally, but i made it happen! And Milestorme, Thank you I only did not read it properly. Mostly because its programming  language like NPM and things like that but hey @milestorme  @FrancescoBorzi  I am slowly learning. I am so proud of myself because I deal with a lot of depression and doing this helps me focus on something new!

**Comment by FrancescoBorzi** [comment]
@crotin1111 to run it normally you don't have to deal with the sources. Just download the executable file from the latest release at:

https://github.com/azerothcore/Keira3/releases

**Comment by crotin1111** [comment]
omg u released it?

**Comment by FrancescoBorzi** [comment]
@crotin1111 it's still in Alpha phase but yes, there are releases already. Most of the features aren't there yet but soon more features will be added.

**Comment by crotin1111** [comment]
hell yea! thats amazing man congrats!
