### ISSUE TITLE
SAI: Dynamic name & Tooltip for target

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/Keira3#611]
In some new custom targets that we are implementing, they use target_o for something different than orientation, so we need to make that a dynamic name and tooltip so we can explain what it does.

While we're doing target_o that way, I suggest we do Xyz also just to be prepared :)

**Comment by FrancescoBorzi** [comment]
@Kitzunu can you give just one an example of when those values should change their name and have a tooltip?

So I'll implement it in order to test the funcionality

**Comment by Kitzunu** [comment]
Yh sure, 2 sec

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/2879
SMART_TARGET_PLAYER_WITH_AURA (spellid, negation?, distMax, distMin) - if target.O is set it will resize the list of targets to target.o

**Comment by FrancescoBorzi** [comment]
mmmh ok, so we need to wait until that one is merged into master

**Comment by FrancescoBorzi** [comment]
![image](https://user-images.githubusercontent.com/75517/82742519-a7bf2f80-9d5f-11ea-9a6c-ddfb01afdc79.png)

**Comment by Kitzunu** [comment]
Cool!
