### ISSUE TITLE
[Bug][Auto-recconnection][Feature review] This seems doesn't work with Beta4

### ISSUE THREAD

**Issue by wlasser** [azerothcore/Keira3#633]
Hello devs!
Sometime ago i am ask about implementation of auto-recconection when Keira is going disconnect.
As i am remember - you are mark as "implemented".
Now i am return to use this software and... Still disconnected and no recconected automatically.
No VPN, direct connection (on two different workstation) and no timeout connection from server.
Affter background (i don't know about foreground process work) for 5-10 minutes - Keira is go disconnected and no reconnect.
This is realy anoying.
Reloading option is kick you on start page, this is look something "pointless".
Anyway, thanks for good app!

**Comment by FrancescoBorzi** [comment]
Thanks for the report. Did it work fine in Beta3?

**Comment by wlasser** [comment]
Hello.
Happy hollidays.
Just check with Beta3 - the problem presented too.

**Comment by FrancescoBorzi** [comment]
hello, sorry but I can't reproduce this issue. I've tried on latest master and it works fine:

![image](https://user-images.githubusercontent.com/75517/80275601-af4cd380-86e2-11ea-9244-8850cab1f22a.png)

I've also tried with the Beta4 release, working for me as well. I'm not sure what the issue could be in your case.

What I tried is:

- connecting to my local MySQL server
- shutting down my local MySQL server
- starting up my local MySQL server

result: Keira3 correctly alert on disconnection and reconnects automatically

**Comment by wlasser** [comment]
First, as i am not to remind: this is windows version (i am not know about linux).
On Beta3/Beta4 i am never see this message like present on you pics.
This screens taken with diif 3-5 secs. 
![2](https://user-images.githubusercontent.com/1104525/80285994-1a20fd80-8729-11ea-9c49-cf01e16e7ee3.png)
![1](https://user-images.githubusercontent.com/1104525/80285995-1beac100-8729-11ea-8129-25ea8cabf5fa.png)

**Comment by FrancescoBorzi** [comment]
@wlasser can you try it in the latest version (beta 4) ? your screenshot is not from the latest version

also can you open the console (ctrl+maiusc+i) and see if there are errors?

**Comment by wlasser** [comment]
```

  | (anonymous) | @ | main.ad6bc31….js:1
-- | -- | -- | --
  | t.__tryOrUnsub | @ | main.ad6bc31….js:1
  | t.error | @ | main.ad6bc31….js:1
  | t._error | @ | main.ad6bc31….js:1
  | t.error | @ | main.ad6bc31….js:1
  | t._error | @ | main.ad6bc31….js:1
  | t.error | @ | main.ad6bc31….js:1
  | t._error | @ | main.ad6bc31….js:1
  | t.error | @ | main.ad6bc31….js:1
  | (anonymous) | @ | main.ad6bc31….js:1
  | e.invoke | @ | polyfills.06ba8d1….js:1
  | onInvoke | @ | main.ad6bc31….js:1
  | e.invoke | @ | polyfills.06ba8d1….js:1
  | t.run | @ | polyfills.06ba8d1….js:1
  | e.run | @ | main.ad6bc31….js:1
  | (anonymous) | @ | main.ad6bc31….js:1
  | (anonymous) | @ | C:\Users\xorx\AppDat…b\Connection.js:526
  | (anonymous) | @ | C:\Users\xorx\AppDat…b\Connection.js:488
  | Sequence.end | @ | C:\Users\xorx\AppDat…nces\Sequence.js:83
  | Protocol.handleNetworkError | @ | C:\Users\xorx\AppDat…col\Protocol.js:369
  | Connection._handleNetworkError | @ | C:\Users\xorx\AppDat…b\Connection.js:418
  | emit | @ | events.js:210
  | emitErrorNT | @ | internal/streams/destroy.js:92
  | emitErrorAndCloseNT | @ | internal/streams/destroy.js:60
  | processTicksAndRejections | @ | internal/process/task_queues.js:80


```

**Comment by FrancescoBorzi** [comment]
I'm not really sure how to reproduce this issue :(
