### ISSUE TITLE
"Help" tab

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/Keira3#658]
The "Help" tab in the top bar points only to Electron and nothing to Keira.

![image](https://user-images.githubusercontent.com/24550914/80849679-89f72280-8c18-11ea-9b7f-64f580d5f514.png)

**Comment by Helias** [comment]
We'll take care of it

**Comment by FrancescoBorzi** [comment]
yeah... we should fix it, the thing is we should rewrite the full Menu.. but we want to keep some of the current functionality (because the menu also determines the keyboard shortcuts)

**Comment by Yehonal** [comment]
I'm quite sure that you can disable/override elements of that menu. Google for it

**Comment by FrancescoBorzi** [comment]
> I'm pretty sure that you can disable/override elements of that menu. Google for it

yes I did a quick search some time ago, there should be a library that allows it. We have to do it indeed
