### ISSUE TITLE
Keira for BFA

### ISSUE THREAD

**Issue by bobo33160** [azerothcore/Keira3#737]
good evening, do you have a Keira that works for bfa, I'm looking for one if I can't find

**Comment by bobo33160** [comment]
Thank you a lot

**Comment by Helias** [comment]
AzerothCore support Wotlk 3.3.5a, so Keira3 does, I don't know if in future Keira3 will support other versions.

**Comment by FrancescoBorzi** [comment]
hello! thanks for writing us, please read this:

https://github.com/azerothcore/forum/issues/43
