### ISSUE TITLE
Suggestion: Message after Execute

### ISSUE THREAD

**Issue by crotin1111** [azerothcore/Keira3#80]
I have a suggestion, When pressing the execute button
I would like a message saying something similar to this "Your query has been successful!"
so people dont have to check in their database wether it was added or not :)

**Comment by FrancescoBorzi** [comment]
@crotin1111 the query is always successful, if it's not you will see an error.

Also after it executes the query, it reloads the entity (so you will see the new data).

So you can assume: no error = everything worked fine.

**Comment by crotin1111** [comment]
\awesome!

**Comment by FrancescoBorzi** [comment]
I was planning to use `angular2-notifications` for this but it's currently blocked by:

https://github.com/flauc/angular2-notifications/issues/348
