### ISSUE TITLE
[Bug] SAI Timed Actionlist

### ISSUE THREAD

**Issue by Jinnaix** [azerothcore/Keira3#803]
There is a (null) reference for situations where creatures have more than one actionlist.

 While Keira3 recognize the creature in the first list, it doesnt anymore in the second. This also results in broken comment generation.

1
![image](https://user-images.githubusercontent.com/37972361/88037254-f3fed400-cb44-11ea-9ebd-976009718f4e.png)

2
![image](https://user-images.githubusercontent.com/37972361/88037343-0b3dc180-cb45-11ea-9ff7-2b51a14cc3f1.png)

3
![image](https://user-images.githubusercontent.com/37972361/88037365-109b0c00-cb45-11ea-96b6-f297e67f99a2.png)

comments
![image](https://user-images.githubusercontent.com/37972361/88037826-b3538a80-cb45-11ea-93e1-beb771c88033.png)

Since i dont work with Azerothcore database, i dont have an example creature for this case.
But this query here can be used for testing:

```sql
DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 1842);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(1842, 0, 0, 0, 34, 0, 100, 0, 8, 16777215, 0, 0, 0, 43, 0, 2402, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Highlord Taelan Fordring - On Reached Point 16777215 - Mount To Model 2402');

DELETE FROM `smart_scripts` WHERE (`source_type` = 9 AND `entryorguid` = 184200);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(184200, 9, 0, 0, 0, 0, 100, 0, 1000, 1000, 0, 0, 0, 1, 4, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Highlord Taelan Fordring - Actionlist - Say Line 4');

DELETE FROM `smart_scripts` WHERE (`source_type` = 9 AND `entryorguid` = 184201);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(184201, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Script9 - Evade');
```

**Comment by Kitzunu** [comment]
Thank you!

**Comment by FrancescoBorzi** [comment]
@Jinnaix thank you very much for this bug report. Very detailed and I loved that you provided the SQL code to reproduce it.

I was indeed able to reproduce it locally, it even gives a console error:

![image](https://user-images.githubusercontent.com/75517/88457747-30a23680-ce89-11ea-94ba-589a249ac29d.png)

I will work on this.

**Comment by FrancescoBorzi** [comment]
More specifically, when opening `184200` the query to get the name is correct:

![image](https://user-images.githubusercontent.com/75517/88457792-a8706100-ce89-11ea-9e83-cd9c491b2c6c.png)

```sql
SELECT name FROM creature_template WHERE entry = 1842
```

while when opening `184201` it generates a bad query:

```sql
SELECT name FROM creature_template WHERE entry = 1842.01
```

![image](https://user-images.githubusercontent.com/75517/88457827-d8b7ff80-ce89-11ea-91b3-0963e048d6c8.png)

Just FYI @Kitzunu @Jinnaix when you select "Enable Keira3 Debug mode" from the Dashboard, you will see all queries that Keira3 executes from the console

**Comment by FrancescoBorzi** [comment]
Fixed: https://github.com/azerothcore/Keira3/pull/811

**Comment by Kitzunu** [comment]
How to see the console from the release exe?

**Comment by Jinnaix** [comment]
I know how important a detailed issue for developing is, so i try to provide good feedback and steps for reproduction, even if i dont understand the programming language behind this. Im happy to help.

@Kitzunu 

![image](https://user-images.githubusercontent.com/37972361/88465667-ff475c00-cec4-11ea-84dc-8cccbcc5ff18.png)
