### ISSUE TITLE
DisplayID

### ISSUE THREAD

**Issue by Wowkasu** [azerothcore/Keira3#813]
Hi, I found a little flaw. 
Linked to new images, for new items.
![2020-07-27_19-19-43](https://user-images.githubusercontent.com/68443208/88545042-a272af80-d044-11ea-811e-0e1e4de3492e.png)
http://acdb.wowka.su/?item=39733
http://acdb.wowka.su/?item=139733

![2020-07-27_19-22-37](https://user-images.githubusercontent.com/68443208/88545216-e06fd380-d044-11ea-8a72-6ae44c74ba26.png)
http://acdb.wowka.su/?item=58159

**Comment by FrancescoBorzi** [comment]
`58159` is a custom Item so Keira3 can't figure out its icon.

The item does not exist in a clean DB: https://wowgaming.altervista.org/aowow/?item=58159

**Comment by Wowkasu** [comment]
Tell me, is there any way to download the made-up icons? - This would be very useful for modified servers.

**Comment by FrancescoBorzi** [comment]
sorry we don't have such feature and implementing it would take quite some time
