### ISSUE TITLE
AzerothCore Data Base Balanced Items

### ISSUE THREAD

**Issue by admdbreno** [azerothcore/Keira3#860]
Good afternoon friends, if anyone can help me I thank you. i wonder if there is an equation to balance items, for example... an item with ItemLevel 284 has its lower version with ItemLevel 271, what is the equation used to balance these items?****

**Comment by Helias** [comment]
Hello, about item level we discussed a bit here: https://github.com/azerothcore/Keira3/issues/405
But I am not aware about a formula to calculate or make an item with a specified item level

**Comment by FrancescoBorzi** [comment]
hi, this is not the right place to ask such questions. Here is to report bugs / feature requests only.

You can use either Discord or our Forum for this kind of topic.
