### ISSUE TITLE
Feature Request: Clone/Copy Options

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/Keira3#964]
Sometimes an existing NPC does most of what you want, for example, you may want to clone a general goods merchant but change its ID, name, and displayID.

In this case, a clone/duplicate button being able to change the ID will achieve your goal very quickly.

Super quickly.

Instead of having to manually recreate hundreds of options yourself you can just clone 90% of the needed info.

This should work for profession trainers, vendors, class trainers, town guards and gossip menus, etc.

BEWARE; Some copied info is super dangerous and may cause issues.

**Comment by FrancescoBorzi** [comment]
actually a similar feature was already requested here: https://github.com/azerothcore/Keira3/issues/25

I'm going to copy your comment there
