### ISSUE TITLE
Feature Request: DisplayID2 Viewer/Finder

### ISSUE THREAD

**Issue by ghost** [azerothcore/Keira3#965]
Ever since Wowhead patched the ability to do &xml to find DisplayID2 models it's super hard to find them.

It's very valuable when making NPCs to be able to either preview the DisplayIDs or even be able to find them when compared to an NPC entryID or name.

A way to find and view models a little bit like how TrinityCreator does would go a long way towards being able to make content.

Thank you.

**Comment by Helias** [comment]
duplicate of https://github.com/azerothcore/Keira3/issues/3016
