### ISSUE TITLE
ENTRY ID Errors (Easy Fix)

### ISSUE THREAD

**Issue by ghost** [azerothcore/Keira3#984]
Keira 3 allows you to put extremely large entry IDs for creatures/items such as 18888800003.

This is too big for wow's database to accept the heidiSQL will throw up an error if you try to import the changes.

It could be worth limiting the input of entryIDs to match the maximum size of entryIDs compatible with the database or at least a warning in the info section of ENTRYID.

Field | Type | Null | Key | Default | Extra | Comment
-- | -- | -- | -- | -- | -- | --
entry | mediumint(8) unsigned | NO | PRI | 0

mediumint   | 3 bytes  -8388608 to 8388607                          0 to 16777215

https://www.azerothcore.org/wiki/creature_template#entry

https://stackoverflow.com/questions/2991405/what-is-the-difference-between-tinyint-smallint-mediumint-bigint-and-int-in-m

**Comment by FrancescoBorzi** [comment]
it sounds quite reasonable
