### ISSUE TITLE
Request: Quests Add Previous Quest/Next Quest 

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/Keira3#988]
Quest Chains are very important to WoW.

Add the ability to specify previous/next quest in the Quest Creator in Keira 3.

**Comment by Helias** [comment]
On Quest Template Addon you can specify Next and PrevQuest

![image](https://user-images.githubusercontent.com/519778/100525518-ca744a00-31c1-11eb-9726-751f4ba0962d.png)

**Comment by FrancescoBorzi** [comment]
closing in favour of: https://github.com/azerothcore/Keira3/issues/989
